using Shouldly;
using Xunit;
using Zphil.LoadBearing.Hosting;
using Zphil.LoadBearing.Rendering;
using Zphil.LoadBearing.Tests.Checking;

namespace Zphil.LoadBearing.Tests.DocHygiene;

/// <summary>
///     Unit and round-trip tests for <see cref="RenderedCitations" />. They pin the managed-block citation
///     scanner — the two bullet shapes a citation renders in, the file line it reports, and the prose it
///     must leave alone — and then chain it to the spec: a rule that carries a <c>Citation</c> is rendered
///     and scanned back, so the gate reading committed bytes is reading what
///     <see cref="Zphil.LoadBearing.Fluent.IEnforceRule.Citation" /> put there.
/// </summary>
public sealed class RenderedCitationsTests
{
    private const char EmDash = (char)0x2014;

    private const string HttpClientPage =
        "https://learn.microsoft.com/dotnet/fundamentals/networking/http/httpclient-guidelines";

    private const string AsyncPage =
        "https://learn.microsoft.com/dotnet/csharp/asynchronous-programming/async-scenarios";

    [Fact]
    public void Extract_EnforceBulletWithCitation_CapturedWithItsFileLine()
    {
        // Arrange: prose above the block, so the reported line is a position in the file rather than an
        // index into the body the markers wrap.
        string[] lines =
        [
            "# Meridian",
            "",
            "Hand-written prose above the block.",
            "",
            ManagedBlock.BeginMarker,
            "*Generated by `loadbearing render` from `Spec`.*",
            "",
            "### Rules",
            $"- `http/reuse-httpclient` {EmDash} Types must not construct `HttpClient`. "
            + $"A new client per call exhausts sockets. See <{HttpClientPage}>.",
            ManagedBlock.EndMarker
        ];
        string doc = string.Join("\n", lines);

        // Act
        IReadOnlyList<RenderedCitation> citations = RenderedCitations.Extract("examples/Ex/AGENTS.md", doc);

        // Assert
        RenderedCitation citation = citations.ShouldHaveSingleItem();
        citation.Doc.ShouldBe("examples/Ex/AGENTS.md");
        citation.DocLine.ShouldBe(9);
        citation.RuleId.ShouldBe("http/reuse-httpclient");
        citation.Url.ShouldBe(HttpClientPage);
    }

    [Fact]
    public void Extract_MigrateBulletWithCitation_CapturedFromMidBullet()
    {
        // Arrange: a Migrate rule renders the citation between the reason and the boy-scout policy, so a
        // pattern anchored at the end of the bullet would drop every migration's page.
        string doc = Card(
            $"- `async/no-sync-over-async` {EmDash} Some existing code here still follows the OLD pattern: "
            + "The adapter blocks on async work. That is grandfathered debt, not house style. "
            + "New code must follow: Types must not use `Task.Wait()`. "
            + $"Blocking a pooled thread deadlocks under load. See <{AsyncPage}>. "
            + "If you are already editing a grandfathered site and the migration is small, migrate it; "
            + "otherwise do not grow the debt.");

        // Act
        IReadOnlyList<RenderedCitation> citations = RenderedCitations.Extract("AGENTS.md", doc);

        // Assert
        RenderedCitation citation = citations.ShouldHaveSingleItem();
        citation.RuleId.ShouldBe("async/no-sync-over-async");
        citation.Url.ShouldBe(AsyncPage);
    }

    [Fact]
    public void Extract_AutolinkOutsideTheMarkers_Ignored()
    {
        // Arrange: hand-written prose beside a block cites pages too, and nothing re-renders it — holding
        // those to a live page is the quote gates' business, not this one's.
        string[] lines =
        [
            $"- `http/reuse-httpclient` {EmDash} a hand-written restatement. See <{HttpClientPage}>.",
            "",
            ManagedBlock.BeginMarker,
            $"- `naming/async-suffix` {EmDash} Methods returning `Task` must be named `*Async`.",
            ManagedBlock.EndMarker,
            "",
            $"More prose. See <{AsyncPage}>."
        ];
        string doc = string.Join("\n", lines);

        // Act
        IReadOnlyList<RenderedCitation> citations = RenderedCitations.Extract("README.md", doc);

        // Assert
        citations.ShouldBeEmpty();
    }

    [Fact]
    public void Extract_TextWithNoManagedBlock_YieldsNothing()
    {
        // Arrange
        var doc = $"# A hand-written page\n\n- `some/rule` {EmDash} not inside a managed block. See <{AsyncPage}>.";

        // Act
        IReadOnlyList<RenderedCitation> citations = RenderedCitations.Extract("d.md", doc);

        // Assert
        citations.ShouldBeEmpty();
    }

    [Fact]
    public void Extract_RenderedEnforceRule_LiftsThePageItsCitationNamed()
    {
        // Arrange: the round trip that ties this scanner to the spec — a rule's Citation, through the
        // renderer and the splice, back out as the page the gate will probe.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("http/reuse-httpclient")
                .Enforce(arch.Namespace("MyApp.*").MustHaveSuffix("Client"))
                .Because("A new client per call exhausts sockets.")
                .Citation(HttpClientPage));
        string body = AgentContextRenderer.RootBlock(model, "Spec");
        string doc = ManagedBlock.Splice(null, body);

        // Act
        IReadOnlyList<RenderedCitation> citations = RenderedCitations.Extract("AGENTS.md", doc);

        // Assert
        RenderedCitation citation = citations.ShouldHaveSingleItem();
        citation.RuleId.ShouldBe("http/reuse-httpclient");
        citation.Url.ShouldBe(HttpClientPage);
    }

    [Fact]
    public void Extract_RenderedMigrateRule_LiftsThePageItsCitationNamed()
    {
        // Arrange: the same round trip for the other posture, whose bullet continues past the citation
        // into the boy-scout policy.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("async/no-blocking-waits")
                .Migrate("Handlers block on the task.", arch.Types.MustHaveSuffix("Handler"))
                .Because("Blocking a pooled thread on an incomplete task deadlocks under load.")
                .Citation(AsyncPage));
        string body = AgentContextRenderer.RootBlock(model, "Spec");
        string doc = ManagedBlock.Splice(null, body);

        // Act
        IReadOnlyList<RenderedCitation> citations = RenderedCitations.Extract("AGENTS.md", doc);

        // Assert
        RenderedCitation citation = citations.ShouldHaveSingleItem();
        citation.RuleId.ShouldBe("async/no-blocking-waits");
        citation.Url.ShouldBe(AsyncPage);
    }

    private static string Card(params string[] bodyLines)
    {
        return string.Join(
            "\n",
            [ManagedBlock.BeginMarker, .. bodyLines, ManagedBlock.EndMarker]);
    }
}
