using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Zphil.LoadBearing.Roslyn.Extraction;

/// <summary>
///     Whether one <see cref="SyntaxTree" /> is generator output, by the two signals a compilation can
///     answer from: <em>provenance</em> — the workspace reported the tree as a source-generated document —
///     and the <em>banner</em>, the tool-independent marker comment convention that predates source
///     generators and that Roslyn's own analyzer infrastructure reads.
/// </summary>
/// <remarks>
///     <para>
///         Both signals are claims about a <em>file</em>. <see cref="FragmentExtractor" /> lifts them to a
///         claim about a type only when they hold of <em>every</em> file declaring it (GRAMMAR §5.2), which
///         is what keeps an author's partial class authored when a generator completes it in a second file.
///     </para>
///     <para>
///         Nothing here reads a file path: a path answer is sound for "may a tool edit this file" and
///         unsound for the question this asks, "is this a rule subject".
///     </para>
///     <para>
///         This file's own header must never spell the banner text: the constants below are the only place
///         it appears, and a copy in a comment above the first token would mark this file's own types
///         generated.
///     </para>
/// </remarks>
internal static class GeneratedSourceSignals
{
    // The two spellings the convention has ever carried, matched as substrings so the self-closing,
    // spaced and paired forms all hit. Ordinal and case-sensitive, matching Roslyn's own reader — every
    // tool in the wild emits them lowercase.
    private const string HyphenatedBanner = "<auto-generated";
    private const string UnhyphenatedBanner = "<autogenerated";

    /// <summary>
    ///     Whether <paramref name="tree" /> is generator output. <paramref name="generatorOutputTrees" /> is
    ///     the provenance set the workspace reported for the containing project, and is
    ///     <see langword="null" /> wherever nothing was loaded to answer with — a hand-built compilation, or
    ///     a replayed build log — leaving the banner as the only signal.
    /// </summary>
    public static bool IsGeneratedTree(SyntaxTree tree, IReadOnlySet<SyntaxTree>? generatorOutputTrees)
    {
        if (generatorOutputTrees is not null && generatorOutputTrees.Contains(tree)) return true;

        return HasGeneratedBanner(tree);
    }

    // The banner is only a banner where it leads the file, so this reads the leading trivia of the first
    // token and nothing else: a mention anywhere further down is prose about the convention, not a claim
    // under it. Directive trivia is skipped rather than stopping the scan — a Razor view opens with
    // #pragma checksum and puts its banner on the line after.
    private static bool HasGeneratedBanner(SyntaxTree tree)
    {
        foreach (SyntaxTrivia trivia in tree.GetRoot().GetLeadingTrivia())
        {
            if (!IsComment(trivia)) continue;

            var text = trivia.ToString();
            if (text.Contains(HyphenatedBanner, StringComparison.Ordinal)) return true;
            if (text.Contains(UnhyphenatedBanner, StringComparison.Ordinal)) return true;
        }

        return false;
    }

    private static bool IsComment(SyntaxTrivia trivia)
    {
        return trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia);
    }
}
