using Shouldly;
using Xunit;

namespace Zphil.LoadBearing.Tests.Cli;

/// <summary>
///     End-to-end <c>render</c> against the real MyApp fixture solution (one class, so xUnit serializes
///     the runs that share the bin-copied tree; each test establishes its own AGENTS.md state). Proves
///     the acceptance boxes: a fresh render writes the pinned root and scope files with the right stdout
///     lines; a re-render is a byte-identical zero diff (<c>unchanged</c>); hand content around the
///     markers survives byte-for-byte (LF and CRLF); a no-scope spec writes the root file only.
/// </summary>
[Collection("Serial")]
public sealed class RenderCommandE2ETests
{
    private const string RootBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppRenderSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Architecture (LoadBearing)\n\n" +
        "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
        "### Layers\n" +
        "- **Domain** — `MyApp.Domain.*`\n" +
        "- **Web** — `MyApp.Web.*`\n\n" +
        "### Rules\n" +
        "- `layering/billing-independent` — Types in `MyApp.Legacy.Billing.*` must not reference " +
        "types in `MyApp.Web.*`. Billing must not reach up into the web layer.\n" +
        "- `naming/interfaces` — Interfaces in `MyApp.*` must be named `I*`. " +
        "House naming convention; agents grep by I-prefix.\n\n" +
        "### Migrations\n" +
        "- `data-access/no-inline-sql` — Most existing code here follows the OLD pattern: " +
        "Controllers build DataTables inline (legacy Active Record style). " +
        "That is grandfathered debt, not house style. New code must follow: " +
        "Types in `MyApp.Web.*` named `*Controller` must not reference types in `System.Data.*`. " +
        "Repository pattern for testability. " +
        "If you are already editing a grandfathered site and the migration is small, migrate it; " +
        "otherwise do not grow the debt.\n\n" +
        "### Frozen scopes\n" +
        "- `legacy/billing` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or `BillingFacade` " +
        "must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or `BillingFacade`. " +
        "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing. " +
        "Sanctioned surface: `IBillingFacade`, `BillingFacade`.";

    private const string ScopeBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppRenderSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Frozen scope `legacy/billing`\n\n" +
        "This directory holds the frozen `legacy/billing` scope. Here be dragons — do not spread references into it.\n\n" +
        "Dragons: Banker's rounding happens at line-item level, NOT invoice level. " +
        "Nightly reconciliation depends on this. Do not normalize.\n\n" +
        "- `legacy/billing/containment` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or " +
        "`BillingFacade` must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or " +
        "`BillingFacade`. Replacement scheduled (BillingV2, ADR-019); not worth stabilizing.\n" +
        "- Sanctioned surface: `IBillingFacade`, `BillingFacade`.\n" +
        "- Expand: `loadbearing explain legacy/billing/containment`.";

    // The MyAppLayerSpec render targets: the root block (module map + two anchored Enforce
    // laws + the frozen-scope law), the Web layer's local-rules card, and the Billing directory's merged
    // block — its Billing layer card BEFORE the frozen-scope card. Each body carries its own provenance
    // line (the non-root files get it prepended, exactly like a scope-only file). The frozen scope here
    // is over the Billing *layer*, so its containment law reads "…in the Billing layer…".
    private const string LayerRootBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppLayerSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Architecture (LoadBearing)\n\n" +
        "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
        "### Layers\n" +
        "- **Web** — `MyApp.Web.*`\n" +
        "- **Billing** — `MyApp.Legacy.Billing.*`\n\n" +
        "### Rules\n" +
        "- `layering/web-not-billing` — The Web layer must not reference types in `MyApp.Legacy.Billing.*`. " +
        "The web layer must reach billing only through the sanctioned facade.\n" +
        "- `layering/billing-not-web` — The Billing layer must not reference types in `MyApp.Web.*`. " +
        "Billing must not reach up into the web layer.\n\n" +
        "### Frozen scopes\n" +
        "- `legacy/billing` — Types in the Billing layer, except `IBillingFacade` or `BillingFacade` " +
        "must be referenced only by the Billing layer, `IBillingFacade` or `BillingFacade`. " +
        "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing. " +
        "Sanctioned surface: `IBillingFacade`, `BillingFacade`.";

    private const string WebCardBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppLayerSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Layer `Web`\n\n" +
        "This directory holds the `Web` layer. Its architecture rules:\n\n" +
        "- `layering/web-not-billing` — The Web layer must not reference types in `MyApp.Legacy.Billing.*`. " +
        "The web layer must reach billing only through the sanctioned facade.\n" +
        "- Expand any rule above with `loadbearing explain <rule-id>`.";

    private const string BillingMergedBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppLayerSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Layer `Billing`\n\n" +
        "This directory holds the `Billing` layer. Its architecture rules:\n\n" +
        "- `layering/billing-not-web` — The Billing layer must not reference types in `MyApp.Web.*`. " +
        "Billing must not reach up into the web layer.\n" +
        "- Expand any rule above with `loadbearing explain <rule-id>`.\n\n" +
        "## Frozen scope `legacy/billing`\n\n" +
        "This directory holds the frozen `legacy/billing` scope. Here be dragons — do not spread references into it.\n\n" +
        "Dragons: Banker's rounding happens at line-item level, NOT invoice level. " +
        "Nightly reconciliation depends on this. Do not normalize.\n\n" +
        "- `legacy/billing/containment` — Types in the Billing layer, except `IBillingFacade` or `BillingFacade` " +
        "must be referenced only by the Billing layer, `IBillingFacade` or `BillingFacade`. " +
        "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing.\n" +
        "- Sanctioned surface: `IBillingFacade`, `BillingFacade`.\n" +
        "- Expand: `loadbearing explain legacy/billing/containment`.";

    private static string SolutionDirectory => Path.GetDirectoryName(CliRunner.MyAppSolution)!;
    private static string RootAgents => Path.Combine(SolutionDirectory, "AGENTS.md");
    private static string ScopeAgents => Path.Combine(SolutionDirectory, "MyApp.Legacy.Billing", "AGENTS.md");
    private static string WebAgents => Path.Combine(SolutionDirectory, "MyApp.Web", "AGENTS.md");
    private static string DomainAgents => Path.Combine(SolutionDirectory, "MyApp.Domain", "AGENTS.md");

    [Fact]
    public async Task Render_Fresh_WritesPinnedRootAndScopeFiles()
    {
        Delete(RootAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        result.Exit.ShouldBe(0);
        Normalize(result.Out).ShouldBe("wrote AGENTS.md\nwrote MyApp.Legacy.Billing/AGENTS.md");
        File.ReadAllText(RootAgents).ShouldBe(Wrap(RootBody, "\n"));
        File.ReadAllText(ScopeAgents).ShouldBe(Wrap(ScopeBody, "\n"));
    }

    [Fact]
    public async Task Render_Twice_IsAZeroDiffUnchanged()
    {
        Delete(RootAgents, ScopeAgents);
        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);
        byte[] rootFirst = File.ReadAllBytes(RootAgents);
        byte[] scopeFirst = File.ReadAllBytes(ScopeAgents);

        CliResult second = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        second.Exit.ShouldBe(0);
        Normalize(second.Out).ShouldBe("unchanged AGENTS.md\nunchanged MyApp.Legacy.Billing/AGENTS.md");
        File.ReadAllBytes(RootAgents).ShouldBe(rootFirst);
        File.ReadAllBytes(ScopeAgents).ShouldBe(scopeFirst);
    }

    [Fact]
    public async Task Render_PreservesHandContentAroundMarkers_Lf()
    {
        Delete(RootAgents, ScopeAgents);
        File.WriteAllText(RootAgents, Seeded("\n"));

        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        File.ReadAllText(RootAgents).ShouldBe(SeededAfterRender("\n"));
    }

    [Fact]
    public async Task Render_PreservesHandContentAroundMarkers_Crlf()
    {
        Delete(RootAgents, ScopeAgents);
        File.WriteAllText(RootAgents, Seeded("\r\n"));

        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        File.ReadAllText(RootAgents).ShouldBe(SeededAfterRender("\r\n"));
    }

    [Fact]
    public async Task Render_SpecWithoutScopes_WritesRootFileOnly()
    {
        Delete(RootAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.CleanSpecDll);

        result.Exit.ShouldBe(0);
        Normalize(result.Out).ShouldBe("wrote AGENTS.md");
        File.Exists(ScopeAgents).ShouldBeFalse();
    }

    [Fact]
    public async Task Render_LayerSpec_WritesRootLayerAndMergedFiles()
    {
        Delete(RootAgents, WebAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.LayerSpecDll);

        result.Exit.ShouldBe(0);
        // Root first, then the layer files (declaration order: Web before Billing), then the Billing
        // directory whose layer + freeze units merged into one wrote-line.
        Normalize(result.Out).ShouldBe(
            "wrote AGENTS.md\nwrote MyApp.Web/AGENTS.md\nwrote MyApp.Legacy.Billing/AGENTS.md");
        File.ReadAllText(RootAgents).ShouldBe(Wrap(LayerRootBody, "\n"));
        File.ReadAllText(WebAgents).ShouldBe(Wrap(WebCardBody, "\n"));
        File.ReadAllText(ScopeAgents).ShouldBe(Wrap(BillingMergedBody, "\n"));
    }

    [Fact]
    public async Task Render_LayerSpecTwice_IsAZeroDiffUnchanged()
    {
        Delete(RootAgents, WebAgents, ScopeAgents);
        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.LayerSpecDll);

        CliResult second = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.LayerSpecDll);

        second.Exit.ShouldBe(0);
        Normalize(second.Out).ShouldBe(
            "unchanged AGENTS.md\nunchanged MyApp.Web/AGENTS.md\nunchanged MyApp.Legacy.Billing/AGENTS.md");
    }

    [Fact]
    public async Task Render_LayersWithoutAnchoredRules_WriteNoLayerCards()
    {
        // MyAppRenderSpec declares Domain and Web layers but anchors no rule on either (and freezes
        // billing), so render emits the root and the billing scope card only — never a layer card.
        Delete(RootAgents, WebAgents, DomainAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        result.Exit.ShouldBe(0);
        Normalize(result.Out).ShouldBe("wrote AGENTS.md\nwrote MyApp.Legacy.Billing/AGENTS.md");
        File.Exists(WebAgents).ShouldBeFalse();
        File.Exists(DomainAgents).ShouldBeFalse();
    }

    private static string Wrap(string body, string nl)
    {
        return $"<!-- loadbearing:begin -->{nl}{body.Replace("\n", nl)}{nl}<!-- loadbearing:end -->{nl}";
    }

    // A hand-authored file with prose above and below the managed block.
    private static string Seeded(string nl)
    {
        return $"# My Project{nl}Hand-written intro.{nl}{nl}" +
               $"<!-- loadbearing:begin -->{nl}OLD BODY{nl}<!-- loadbearing:end -->{nl}{nl}" +
               $"Footer stays put.{nl}";
    }

    private static string SeededAfterRender(string nl)
    {
        return $"# My Project{nl}Hand-written intro.{nl}{nl}" +
               $"<!-- loadbearing:begin -->{nl}{RootBody.Replace("\n", nl)}{nl}<!-- loadbearing:end -->{nl}{nl}" +
               $"Footer stays put.{nl}";
    }

    private static void Delete(params string[] paths)
    {
        foreach (string path in paths)
            if (File.Exists(path))
                File.Delete(path);
    }

    private static string Normalize(string value)
    {
        return value.Replace("\r\n", "\n").Trim();
    }
}