using Shouldly;
using Xunit;
using Zphil.LoadBearing.Rendering;
using Zphil.LoadBearing.Tests.TestSupport;

namespace Zphil.LoadBearing.Tests.Cli;

/// <summary>
///     End-to-end <c>render</c> against the real MyApp fixture solution (one class, so xUnit serializes
///     the runs that share the bin-copied tree; each test establishes its own AGENTS.md state). Proves
///     the acceptance boxes: a fresh render writes the pinned root and scope files with the right stdout
///     lines; a re-render is a byte-identical zero diff (<c>unchanged</c>); hand content around the
///     markers survives byte-for-byte (LF and CRLF); a no-scope spec writes the root file only; and
///     <c>--diagram</c> adds two Mermaid fences — the codebase graph and the spec's law — as a target of
///     its own, with the graph scopeable by project-name glob, the law never scoped, and the scope options
///     refused when no target file is named.
/// </summary>
[Collection("Serial")]
public sealed class RenderCommandE2ETests
{
    private const string RootBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppRenderSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Architecture (LoadBearing)\n\n" +
        "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
        "### Layers\n" +
        "- **Domain** — `MyApp.Domain.*`\n" +
        "- **Web** — `MyApp.Web.*`\n\n" +
        "### Rules\n" +
        "- `layering/billing-independent` — Types in `MyApp.Legacy.Billing.*` must not reference " +
        "types in `MyApp.Web.*`. Billing must not reach up into the web layer.\n" +
        "- `naming/interfaces` — Interfaces in `MyApp.*` must be named `I*`. " +
        "House naming convention; agents grep by I-prefix.\n\n" +
        "### Migrations\n" +
        "- `data-access/no-inline-sql` — Most existing code here follows the OLD pattern: " +
        "Controllers build DataTables inline (legacy Active Record style). " +
        "That is grandfathered debt, not house style. New code must follow: " +
        "Types in `MyApp.Web.*` named `*Controller` must not reference types in `System.Data.*`. " +
        "Repository pattern for testability. " +
        "If you are already editing a grandfathered site and the migration is small, migrate it; " +
        "otherwise do not grow the debt.\n\n" +
        "### Quarantined scopes\n" +
        "- `legacy/billing` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or `BillingFacade` " +
        "must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or `BillingFacade`. " +
        "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing. " +
        "Sanctioned surface: `IBillingFacade`, `BillingFacade`.";

    private const string ScopeBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppRenderSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Quarantined scope `legacy/billing`\n\n" +
        "This directory holds the quarantined `legacy/billing` scope. Here be dragons — do not spread references into it.\n\n" +
        "Dragons: Banker's rounding happens at line-item level, NOT invoice level. " +
        "Nightly reconciliation depends on this. Do not normalize.\n\n" +
        "- `legacy/billing/containment` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or " +
        "`BillingFacade` must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or " +
        "`BillingFacade`. Replacement scheduled (BillingV2, ADR-019); not worth stabilizing.\n" +
        "- Sanctioned surface: `IBillingFacade`, `BillingFacade`.\n" +
        "- Expand: `loadbearing explain legacy/billing/containment`.";

    // The MyAppLayerSpec render targets: the root block (module map + two anchored Enforce
    // laws + the quarantined-scope law), the Web layer's local-rules card, and the Billing directory's merged
    // block — its Billing layer card BEFORE the quarantined-scope card. Each body carries its own provenance
    // line (the non-root files get it prepended, exactly like a scope-only file). The quarantined scope here
    // is over the Billing *layer*, so its containment law reads "…in the Billing layer…".
    private const string LayerRootBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppLayerSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Architecture (LoadBearing)\n\n" +
        "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
        "### Layers\n" +
        "- **Web** — `MyApp.Web.*`\n" +
        "- **Billing** — `MyApp.Legacy.Billing.*`\n\n" +
        "### Rules\n" +
        "- `layering/web-not-billing` — The Web layer must not reference types in `MyApp.Legacy.Billing.*`. " +
        "The web layer must reach billing only through the sanctioned facade.\n" +
        "- `layering/billing-not-web` — The Billing layer must not reference types in `MyApp.Web.*`. " +
        "Billing must not reach up into the web layer.\n\n" +
        "### Quarantined scopes\n" +
        "- `legacy/billing` — Types in the Billing layer, except `IBillingFacade` or `BillingFacade` " +
        "must be referenced only by the Billing layer, `IBillingFacade` or `BillingFacade`. " +
        "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing. " +
        "Sanctioned surface: `IBillingFacade`, `BillingFacade`.";

    private const string WebCardBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppLayerSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Layer `Web`\n\n" +
        "This directory holds the `Web` layer. Its architecture rules:\n\n" +
        "- `layering/web-not-billing` — The Web layer must not reference types in `MyApp.Legacy.Billing.*`. " +
        "The web layer must reach billing only through the sanctioned facade.\n" +
        "- Expand any rule above with `loadbearing explain <rule-id>`.";

    private const string BillingMergedBody =
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppLayerSpec` — " +
        "do not edit between the markers; edit the spec and re-render.*\n\n" +
        "## Layer `Billing`\n\n" +
        "This directory holds the `Billing` layer. Its architecture rules:\n\n" +
        "- `layering/billing-not-web` — The Billing layer must not reference types in `MyApp.Web.*`. " +
        "Billing must not reach up into the web layer.\n" +
        "- Expand any rule above with `loadbearing explain <rule-id>`.\n\n" +
        "## Quarantined scope `legacy/billing`\n\n" +
        "This directory holds the quarantined `legacy/billing` scope. Here be dragons — do not spread references into it.\n\n" +
        "Dragons: Banker's rounding happens at line-item level, NOT invoice level. " +
        "Nightly reconciliation depends on this. Do not normalize.\n\n" +
        "- `legacy/billing/containment` — Types in the Billing layer, except `IBillingFacade` or `BillingFacade` " +
        "must be referenced only by the Billing layer, `IBillingFacade` or `BillingFacade`. " +
        "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing.\n" +
        "- Sanctioned surface: `IBillingFacade`, `BillingFacade`.\n" +
        "- Expand: `loadbearing explain legacy/billing/containment`.";

    // The scoped diagram: MyApp.Domain leaves, so the Domain -> Web edge leaves with it and only the
    // Web -> Legacy.Billing edge survives. Node IDs are recomputed over the projects actually drawn.
    // The law fence below it is byte-identical to the unscoped one: a project-name filter is a statement
    // about the codebase survey, and the law is drawn from the spec, which the filter never touches. That
    // is what lets the second fence name places the first one no longer shows.
    private const string ScopedDiagramBody =
        "*Generated by `loadbearing render` from `MyApp.sln` — " +
        "do not edit between the markers; re-render to update.*\n\n" +
        "```mermaid\n" +
        "flowchart LR\n" +
        "    accTitle: Codebase survey: MyApp.sln\n" +
        "    accDescr: Projects in this solution and their cross-project references.\n" +
        "\n" +
        "    p_MyApp_Legacy_Billing[\"MyApp.Legacy.Billing\"]\n" +
        "    p_MyApp_Web[\"MyApp.Web\"]\n" +
        "\n" +
        "    p_MyApp_Web --> p_MyApp_Legacy_Billing\n" +
        "```\n" +
        "\n" +
        "*Generated by `loadbearing render` from `Zphil.LoadBearing.MyAppRenderSpec`. " +
        "Do not edit between the markers; edit the spec and re-render.*\n" +
        "\n" +
        "```mermaid\n" +
        "flowchart LR\n" +
        "    accTitle: Architecture law: Zphil.LoadBearing.MyAppRenderSpec\n" +
        "    accDescr: The places this spec names, the references it forbids, and the debt it grandfathers.\n" +
        "\n" +
        "    subgraph s_MyApp_Legacy_Billing[\"Quarantine: legacy/billing\"]\n" +
        "        s_IBillingFacade[[\"IBillingFacade\"]]\n" +
        "        s_BillingFacade[[\"BillingFacade\"]]\n" +
        "    end\n" +
        "    s_Web[\"Web\"]\n" +
        "    s_System_Data(\"System.Data.*\")\n" +
        "\n" +
        "    s_MyApp_Legacy_Billing --x s_Web\n" +
        "    s_Web -.-x|\"grandfathered\"| s_System_Data\n" +
        "\n" +
        "    subgraph l_legend[\"Legend\"]\n" +
        "        l_ban[\"--x = must not reference\"]\n" +
        "        l_debt[\"-.-x grandfathered = Migrate debt, with the existing sites baselined\"]\n" +
        "        l_quarantine[\"Quarantine box = a contained scope; the doubled boxes are its sanctioned surface\"]\n" +
        "        l_outside[\"Rounded box = a place named only as the target of a rule\"]\n" +
        "    end\n" +
        "```\n" +
        "\n" +
        "Not drawn in full: `naming/interfaces`, `legacy/billing/tripwire` (Quarantine). " +
        "Expand any of them with `loadbearing explain <rule-id>`.";

    private static string SolutionDirectory => Path.GetDirectoryName(CliRunner.MyAppSolution)!;
    private static string RootAgents => Path.Combine(SolutionDirectory, "AGENTS.md");
    private static string ScopeAgents => Path.Combine(SolutionDirectory, "MyApp.Legacy.Billing", "AGENTS.md");
    private static string WebAgents => Path.Combine(SolutionDirectory, "MyApp.Web", "AGENTS.md");
    private static string DomainAgents => Path.Combine(SolutionDirectory, "MyApp.Domain", "AGENTS.md");
    private static string Architecture => Path.Combine(SolutionDirectory, "ARCHITECTURE.md");

    [Fact]
    public async Task Render_Fresh_WritesPinnedRootAndScopeFiles()
    {
        Delete(RootAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        result.ShouldSucceed();
        result.Out.NormalizedTrimmed()
            .ShouldBe("wrote AGENTS.md\nwrote MyApp.Legacy.Billing/AGENTS.md");
        File.ReadAllText(RootAgents)
            .ShouldBe(Wrap(RootBody, "\n"));
        File.ReadAllText(ScopeAgents)
            .ShouldBe(Wrap(ScopeBody, "\n"));
    }

    [Fact]
    public async Task Render_Twice_IsAZeroDiffUnchanged()
    {
        Delete(RootAgents, ScopeAgents);
        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);
        byte[] rootFirst = File.ReadAllBytes(RootAgents);
        byte[] scopeFirst = File.ReadAllBytes(ScopeAgents);

        CliResult second = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        second.ShouldSucceed();
        second.Out.NormalizedTrimmed()
            .ShouldBe("unchanged AGENTS.md\nunchanged MyApp.Legacy.Billing/AGENTS.md");
        File.ReadAllBytes(RootAgents)
            .ShouldBe(rootFirst);
        File.ReadAllBytes(ScopeAgents)
            .ShouldBe(scopeFirst);
    }

    [Fact]
    public async Task Render_PreservesHandContentAroundMarkers_Lf()
    {
        Delete(RootAgents, ScopeAgents);
        File.WriteAllText(RootAgents, Seeded("\n"));

        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        File.ReadAllText(RootAgents)
            .ShouldBe(SeededAfterRender("\n"));
    }

    [Fact]
    public async Task Render_PreservesHandContentAroundMarkers_Crlf()
    {
        Delete(RootAgents, ScopeAgents);
        File.WriteAllText(RootAgents, Seeded("\r\n"));

        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        File.ReadAllText(RootAgents)
            .ShouldBe(SeededAfterRender("\r\n"));
    }

    [Fact]
    public async Task Render_SpecWithoutScopes_WritesRootFileOnly()
    {
        Delete(RootAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.CleanSpecDll);

        result.ShouldSucceed();
        result.Out.NormalizedTrimmed()
            .ShouldBe("wrote AGENTS.md");
        File.Exists(ScopeAgents)
            .ShouldBeFalse();
    }

    [Fact]
    public async Task Render_LayerSpec_WritesRootLayerAndMergedFiles()
    {
        Delete(RootAgents, WebAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.LayerSpecDll);

        result.ShouldSucceed();
        // Root first, then the layer files (declaration order: Web before Billing), then the Billing
        // directory whose layer + quarantine units merged into one wrote-line.
        result.Out.NormalizedTrimmed()
            .ShouldBe(
                "wrote AGENTS.md\nwrote MyApp.Web/AGENTS.md\nwrote MyApp.Legacy.Billing/AGENTS.md");
        File.ReadAllText(RootAgents)
            .ShouldBe(Wrap(LayerRootBody, "\n"));
        File.ReadAllText(WebAgents)
            .ShouldBe(Wrap(WebCardBody, "\n"));
        File.ReadAllText(ScopeAgents)
            .ShouldBe(Wrap(BillingMergedBody, "\n"));
    }

    [Fact]
    public async Task Render_LayerSpecTwice_IsAZeroDiffUnchanged()
    {
        Delete(RootAgents, WebAgents, ScopeAgents);
        await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.LayerSpecDll);

        CliResult second = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.LayerSpecDll);

        second.ShouldSucceed();
        second.Out.NormalizedTrimmed()
            .ShouldBe(
                "unchanged AGENTS.md\nunchanged MyApp.Web/AGENTS.md\nunchanged MyApp.Legacy.Billing/AGENTS.md");
    }

    [Fact]
    public async Task Render_LayersWithoutAnchoredRules_WriteNoLayerCards()
    {
        // MyAppRenderSpec declares Domain and Web layers but anchors no rule on either (and quarantines
        // billing), so render emits the root and the billing scope card only — never a layer card.
        Delete(RootAgents, WebAgents, DomainAgents, ScopeAgents);

        CliResult result = await CliRunner.InvokeAsync("render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll);

        result.ShouldSucceed();
        result.Out.NormalizedTrimmed()
            .ShouldBe("wrote AGENTS.md\nwrote MyApp.Legacy.Billing/AGENTS.md");
        File.Exists(WebAgents)
            .ShouldBeFalse();
        File.Exists(DomainAgents)
            .ShouldBeFalse();
    }

    [Fact]
    public async Task Render_Diagram_WritesTheGoldenMermaidBlockThenReportsUnchanged()
    {
        // One workspace load covers both halves: the wrote/unchanged pair over an untouched codebase is
        // the idempotence proof, and the diagram target reports on the same stream as the AGENTS.md ones.
        Delete(RootAgents, ScopeAgents, Architecture);

        CliResult first = await CliRunner.InvokeAsync(
            "render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll, "--diagram", Architecture);

        first.ShouldSucceed();
        first.Out.NormalizedTrimmed()
            .ShouldBe("wrote AGENTS.md\nwrote MyApp.Legacy.Billing/AGENTS.md\nwrote ARCHITECTURE.md");
        File.ReadAllText(Architecture)
            .ShouldMatchGolden("diagram.md");

        CliResult second = await CliRunner.InvokeAsync(
            "render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll, "--diagram", Architecture);

        second.ShouldSucceed();
        second.Out.NormalizedTrimmed()
            .ShouldBe(
                "unchanged AGENTS.md\nunchanged MyApp.Legacy.Billing/AGENTS.md\nunchanged ARCHITECTURE.md");
    }

    [Fact]
    public async Task Render_DiagramWithAnAllowList_DrawsOnlyTheNamedProjects()
    {
        Delete(RootAgents, ScopeAgents, Architecture);

        CliResult result = await CliRunner.InvokeAsync(
            "render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll,
            "--diagram", Architecture, "--diagram-only", "MyApp.Web;MyApp.Legacy.Billing");

        result.ShouldSucceed();
        ManagedBlock.ExtractBody(File.ReadAllText(Architecture))
            .ShouldBe(ScopedDiagramBody);
    }

    [Fact]
    public async Task Render_DiagramScopeWithoutATarget_IsAUserError()
    {
        // Validated before the workspace cost: silently ignoring the scope would let a mistyped --diagram
        // draw the whole solution.
        CliResult result = await CliRunner.InvokeAsync(
            "render", CliRunner.MyAppSolution, "--spec", CliRunner.RenderSpecDll, "--diagram-only", "MyApp.Web");

        result.ShouldRefuseWith("--diagram-only and --diagram-exclude apply only with --diagram <path>.");
    }

    private static string Wrap(string body, string nl)
    {
        return $"<!-- loadbearing:begin -->{nl}{body.Replace("\n", nl)}{nl}<!-- loadbearing:end -->{nl}";
    }

    // A hand-authored file with prose above and below the managed block.
    private static string Seeded(string nl)
    {
        return $"# My Project{nl}Hand-written intro.{nl}{nl}" +
               $"<!-- loadbearing:begin -->{nl}OLD BODY{nl}<!-- loadbearing:end -->{nl}{nl}" +
               $"Footer stays put.{nl}";
    }

    private static string SeededAfterRender(string nl)
    {
        return $"# My Project{nl}Hand-written intro.{nl}{nl}" +
               $"<!-- loadbearing:begin -->{nl}{RootBody.Replace("\n", nl)}{nl}<!-- loadbearing:end -->{nl}{nl}" +
               $"Footer stays put.{nl}";
    }

    private static void Delete(params string[] paths)
    {
        foreach (string path in paths)
            if (File.Exists(path))
                File.Delete(path);
    }
}
