using Zphil.LoadBearing.Internal;
using Zphil.LoadBearing.Prose;

namespace Zphil.LoadBearing.Rendering;

/// <summary>
///     Composes the agent-context block bodies from the reified model — the second render target
///     (DESIGN.md §9, R2). Pure and codebase-independent: the root block is a function of
///     <c>(model, specName)</c> (plus an optional grandfathered-count provider), a scope card a function
///     of one containment rule. Output is LF-internal always (never <c>Environment.NewLine</c>); the
///     splicer applies the target file's line ending. The always-on root block carries the module map,
///     the Enforce "must" laws, the Migrate counter-prior paragraphs, and the Freeze containment laws
///     (the frozen-scopes section — the containment law binds code <em>outside</em> the frozen directory,
///     which the per-directory scope card never reaches); dragons prose stays scoped-only (progressive
///     disclosure). The Migrate voice (DESIGN.md §5) explicitly counters the statistical prior — "most
///     code here follows the OLD pattern".
/// </summary>
public static class AgentContextRenderer
{
    private const string Heading = "## Architecture (LoadBearing)";

    private const string GlossaryLine =
        "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.";

    /// <summary>
    ///     The provenance/warning line — the first line inside every managed block (R1). Names the
    ///     spec deterministically (assembly file name without extension) so the pin is
    ///     machine-independent; carries no timestamp or tool version (idempotence).
    /// </summary>
    public static string ProvenanceLine(string specName)
    {
        Guard.NotNullOrWhiteSpace(specName, nameof(specName));

        return $"*Generated by `loadbearing render` from `{specName}` — " +
               "do not edit between the markers; edit the spec and re-render.*";
    }

    /// <summary>
    ///     The root managed-block body: provenance, the H2 heading, the glossary + drill-down pointer
    ///     (GRAMMAR §4.1, once), then — each omitted when empty — the module map (Layers), the Enforce
    ///     laws (Rules), the Migrate counter-prior paragraphs (Migrations), and the Freeze containment
    ///     laws (Frozen scopes — the containment law + sanctioned surface; dragons prose stays scoped).
    ///     <paramref name="grandfatheredCounts" /> is an optional live-count provider: when it returns a
    ///     value for a Migrate rule, the "Grandfathered sites remaining: {n}." sentence is appended. The
    ///     default (null) renders no counts — the maintainer decision for Phase 5, where the burndown
    ///     lives in <c>status</c>/<c>explain</c>, not the block.
    /// </summary>
    public static string RootBlock(
        ArchitectureModel model, string specName, Func<ArchRule, int?>? grandfatheredCounts = null)
    {
        Guard.NotNull(model, nameof(model));

        var sections = new List<string>
        {
            ProvenanceLine(specName),
            Heading,
            GlossaryLine
        };

        if (model.Layers.Count > 0) sections.Add(LayersSection(model.Layers));

        var enforceRules = model.Rules.Where(rule => rule.Posture == Posture.Enforce).ToList();
        if (enforceRules.Count > 0) sections.Add(RulesSection(enforceRules));

        var migrateRules = model.Rules.Where(rule => rule.Posture == Posture.Migrate).ToList();
        if (migrateRules.Count > 0) sections.Add(MigrationsSection(migrateRules, grandfatheredCounts));

        var containmentRules = model.Rules.Where(rule => rule.Freeze is { Role: FreezeRole.Containment }).ToList();
        if (containmentRules.Count > 0) sections.Add(FrozenScopesSection(containmentRules));

        return string.Join("\n\n", sections);
    }

    /// <summary>
    ///     A frozen scope's context card (without the provenance line, which the splice pipeline adds
    ///     once per file): the scope heading, the containment law and rationale, the load-bearing-
    ///     weirdness dragons prose (inline <c>Dragons:</c> paragraph and/or a linked <c>Dragons doc</c>
    ///     bullet — DESIGN.md §5, one of the two is spec-guaranteed), the sanctioned surface (omitted for
    ///     a hermetic freeze), and the <c>explain</c> pointer. This is the scoped, per-directory story the
    ///     agents editing dragon territory read.
    /// </summary>
    public static string ScopeCard(ArchRule containmentRule)
    {
        Guard.NotNull(containmentRule, nameof(containmentRule));
        if (containmentRule.Freeze is not { Role: FreezeRole.Containment } freeze)
            throw new ArgumentException("ScopeCard requires a Freeze containment rule.", nameof(containmentRule));

        string scopeId = freeze.ScopeId;

        var bullets = new List<string>
        {
            $"- {ProseFormat.Backtick(containmentRule.Id)} — {containmentRule.Sentence} {containmentRule.Because}"
        };
        if (freeze.Boundary.Count > 0) bullets.Add($"- Sanctioned surface: {SurfaceList(freeze.Boundary)}.");
        // The linked long-form doc is a backticked solution-relative path (the spec stays the index —
        // DESIGN.md §6), not a rebased markdown link.
        if (freeze.DragonsDoc is { } dragonsDoc) bullets.Add($"- Dragons doc: {ProseFormat.Backtick(dragonsDoc)}.");
        bullets.Add($"- Expand: {ProseFormat.Backtick($"loadbearing explain {containmentRule.Id}")}.");

        var sections = new List<string>
        {
            $"## Frozen scope {ProseFormat.Backtick(scopeId)}",
            $"This directory holds the frozen {ProseFormat.Backtick(scopeId)} scope. " +
            "Here be dragons — do not spread references into it."
        };
        if (freeze.Dragons is { } dragons) sections.Add($"Dragons: {dragons}");
        sections.Add(string.Join("\n", bullets));

        return string.Join("\n\n", sections);
    }

    private static string LayersSection(IReadOnlyList<LayerDefinition> layers)
    {
        var bullets = layers.Select(layer => "- " + layer.DefinitionFragment);
        return "### Layers\n" + string.Join("\n", bullets);
    }

    private static string RulesSection(IReadOnlyList<ArchRule> rules)
    {
        var bullets = rules.Select(rule =>
            $"- {ProseFormat.Backtick(rule.Id)} — {rule.Sentence} {rule.Because}");
        return "### Rules\n" + string.Join("\n", bullets);
    }

    // The Migrate counter-prior section (DESIGN.md §5, Spec 2): one bullet per Migrate rule that names
    // the OLD pattern as grandfathered debt, states the target law, and renders the boy-scout policy —
    // so an agent reading the majority (old) pattern does not infer it is house style.
    private static string MigrationsSection(IReadOnlyList<ArchRule> rules, Func<ArchRule, int?>? counts)
    {
        var bullets = rules.Select(rule => MigrationBullet(rule, counts));
        return "### Migrations\n" + string.Join("\n", bullets);
    }

    private static string MigrationBullet(ArchRule rule, Func<ArchRule, int?>? counts)
    {
        MigrateData migrate = rule.Migrate!;
        string bullet = $"- {ProseFormat.Backtick(rule.Id)} — Most existing code here follows the OLD pattern: " +
                        $"{migrate.From} That is grandfathered debt, not house style. New code must follow: " +
                        $"{migrate.ToSentence} {rule.Because} {PolicySentence(migrate.Policy)}";

        if (counts?.Invoke(rule) is { } remaining) bullet += $" Grandfathered sites remaining: {remaining}.";

        return bullet;
    }

    // The Freeze containment section (DESIGN.md §5, GRAMMAR §7): one bullet per frozen scope stating the
    // containment law + rationale + sanctioned surface, in the always-on root block because containment
    // binds code OUTSIDE the frozen directory — those agents never see the per-directory scope card.
    // Dragons prose stays scoped-only (progressive disclosure) and prints in the scope card + explain.
    private static string FrozenScopesSection(IReadOnlyList<ArchRule> containmentRules)
    {
        var bullets = containmentRules.Select(FrozenScopeBullet);
        return "### Frozen scopes\n" + string.Join("\n", bullets);
    }

    private static string FrozenScopeBullet(ArchRule rule)
    {
        FreezeData freeze = rule.Freeze!;
        var bullet = $"- {ProseFormat.Backtick(freeze.ScopeId)} — {rule.Sentence} {rule.Because}";
        if (freeze.Boundary.Count > 0) bullet += $" Sanctioned surface: {SurfaceList(freeze.Boundary)}.";
        return bullet;
    }

    private static string PolicySentence(MigrationPolicy policy)
    {
        return policy switch
        {
            MigrationPolicy.AlwaysMigrate =>
                "If your change touches a grandfathered site, migrate it as part of the change; never grow the debt.",
            MigrationPolicy.NeverExpand =>
                "Do not migrate grandfathered sites in passing (a coordinated migration is planned); never grow the debt.",
            _ => "If you are already editing a grandfathered site and the migration is small, migrate it; " +
                 "otherwise do not grow the debt."
        };
    }

    private static string SurfaceList(IReadOnlyList<Type> boundary)
    {
        return string.Join(", ", boundary.Select(type => ProseFormat.Backtick(TypeName.Simple(type))));
    }
}