using Zphil.LoadBearing.Internal;
using Zphil.LoadBearing.Model;
using Zphil.LoadBearing.Prose;

namespace Zphil.LoadBearing.Rendering;

/// <summary>
///     Composes the agent-context block bodies from the reified model — the second render target.
///     Pure and codebase-independent: the root block is a function of
///     <c>(model, specName)</c> (plus an optional grandfathered-count provider), a scope card a function
///     of one containment rule. Output is LF-internal always (never <c>Environment.NewLine</c>); the
///     splicer applies the target file's line ending. The always-on root block carries the module map,
///     the Enforce "must" laws, the Migrate counter-prior paragraphs, and the Freeze containment laws
///     (the frozen-scopes section — the containment law binds code <em>outside</em> the frozen directory,
///     which the per-directory scope card never reaches); dragons prose stays scoped-only (progressive
///     disclosure). The Migrate voice explicitly counters the statistical prior — "most
///     code here follows the OLD pattern".
/// </summary>
public static class AgentContextRenderer
{
    private const string Heading = "## Architecture (LoadBearing)";

    // The glossary composes from per-axis clauses, not 2^N whole-string constants: the "reference" clause is
    // always present, "use" iff a member-target rule exists, "construct" iff a ctor rule exists — each axis
    // gates independently, so a spec without a given axis renders byte-identically to before that axis existed
    // (GRAMMAR §4.1/§4.5/§10). The clauses join with "; " and the tail follows a ". " separator.
    private const string GlossaryReferenceClause = "reference = a source-level type reference";

    private const string GlossaryUseClause = "use = a source-level member access";

    private const string GlossaryConstructClause =
        "construct = a source-level object creation (`new`, including target-typed `new()`)";

    private const string GlossaryInjectClause =
        "inject = a source-level constructor-parameter dependency (primary constructors included)";

    private const string GlossaryCatchClause =
        "catch = a source-level `catch` clause (a bare `catch` counts as `System.Exception`)";

    private const string GlossaryThrowClause =
        "throw = a source-level `throw` of the thrown expression's type (bare rethrows `throw;` are not recorded)";

    // A separate, independently-gated glossary line (not an axis clause): rendered as ONE line whenever any
    // rule's subject or operands carry a Registered noun, on the same byte-identical-without-it terms as the
    // axis clauses (GRAMMAR §4.7/§10). The backticked method list is literal output.
    private const string GlossaryRegisteredLine =
        "registered = named in a source-level container registration " +
        "(`AddSingleton`/`AddScoped`/`AddTransient`/`TryAdd*`/`AddHostedService`/`AddDbContext`/`AddHttpClient<TClient>`); " +
        "registrations made by assembly scanning, factory internals, or framework defaults are not seen.";

    private const string GlossaryTail = "Expand any rule ID with `loadbearing explain <rule-id>`.";

    /// <summary>
    ///     The provenance/warning line — the first line inside every managed block. Names the
    ///     spec deterministically (assembly file name without extension) so the pin is
    ///     machine-independent; carries no timestamp or tool version (idempotence).
    /// </summary>
    public static string ProvenanceLine(string specName)
    {
        Guard.NotNullOrWhiteSpace(specName, nameof(specName));

        return $"*Generated by `loadbearing render` from `{specName}` — " +
               "do not edit between the markers; edit the spec and re-render.*";
    }

    /// <summary>
    ///     The root managed-block body: provenance, the H2 heading, the glossary + drill-down pointer
    ///     (GRAMMAR §4.1, once), then — each omitted when empty — the module map (Layers), the Enforce
    ///     laws (Rules), the Migrate counter-prior paragraphs (Migrations), and the Freeze containment
    ///     laws (Frozen scopes — the containment law + sanctioned surface; dragons prose stays scoped).
    ///     <paramref name="grandfatheredCounts" /> is an optional live-count provider: when it returns a
    ///     value for a Migrate rule, the "Grandfathered sites remaining: {n}." sentence is appended. The
    ///     default (null) renders no counts — the maintainer decision, where the burndown
    ///     lives in <c>status</c>/<c>explain</c>, not the block.
    /// </summary>
    public static string RootBlock(
        ArchitectureModel model, string specName, Func<ArchRule, int?>? grandfatheredCounts = null)
    {
        Guard.NotNull(model, nameof(model));

        bool hasMemberRule = model.Rules.Any(rule => rule.Constraint?.MemberOperands.Count > 0);
        bool hasCtorRule = model.Rules.Any(rule => rule.Constraint is MustNotConstructConstraint);
        bool hasInjectRule = model.Rules.Any(rule => rule.Constraint is MustNotInjectConstraint);
        bool hasCatchRule = model.Rules.Any(rule => rule.Constraint is MustNotCatchConstraint);
        bool hasThrowRule = model.Rules.Any(rule => rule.Constraint is MustOnlyThrowConstraint);
        bool hasRegisteredNoun = model.Rules.Any(rule => rule.Constraint is { } constraint && CarriesRegisteredNoun(constraint));
        var sections = new List<string>
        {
            ProvenanceLine(specName),
            Heading,
            GlossaryLine(hasMemberRule, hasCtorRule, hasInjectRule, hasCatchRule, hasThrowRule)
        };

        // The Registered glossary line gates independently of the axis clauses (a Registered noun can ride a
        // non-inject verb, and MustNotInject can ban a plain type), so it is its own paragraph (GRAMMAR §10).
        if (hasRegisteredNoun) sections.Add(GlossaryRegisteredLine);

        if (model.Layers.Count > 0) sections.Add(LayersSection(model.Layers));

        var enforceRules = model.Rules.Where(rule => rule.Posture == Posture.Enforce).ToList();
        if (enforceRules.Count > 0) sections.Add(RulesSection(enforceRules));

        var migrateRules = model.Rules.Where(rule => rule.Posture == Posture.Migrate).ToList();
        if (migrateRules.Count > 0) sections.Add(MigrationsSection(migrateRules, grandfatheredCounts));

        var containmentRules = model.Rules.Where(rule => rule.Freeze is { Role: FreezeRole.Containment }).ToList();
        if (containmentRules.Count > 0) sections.Add(FrozenScopesSection(containmentRules));

        return string.Join("\n\n", sections);
    }

    // The glossary/drill-down line, composed from the always-on "reference" clause plus the axis clauses the
    // spec actually exercises, then the shared tail. Reproduces the pre-ctor "reference." and "reference; use."
    // lines byte-for-byte when their axis flags are the only ones set (GRAMMAR §4.1/§4.5/§10).
    private static string GlossaryLine(
        bool hasMemberRule, bool hasCtorRule, bool hasInjectRule, bool hasCatchRule, bool hasThrowRule)
    {
        var clauses = new List<string> { GlossaryReferenceClause };
        if (hasMemberRule) clauses.Add(GlossaryUseClause);
        if (hasCtorRule) clauses.Add(GlossaryConstructClause);
        if (hasInjectRule) clauses.Add(GlossaryInjectClause);
        if (hasCatchRule) clauses.Add(GlossaryCatchClause);
        if (hasThrowRule) clauses.Add(GlossaryThrowClause);

        return string.Join("; ", clauses) + ". " + GlossaryTail;
    }

    // True when a rule's subject or any operand carries a Registered noun (GRAMMAR §10) — descending through
    // Except payloads and the internal Freeze union, since a Registered noun in any of those still renders the
    // word "registered" in the block's prose and so must gate the glossary line.
    private static bool CarriesRegisteredNoun(Constraint constraint)
    {
        return SelectionCarriesRegisteredNoun(constraint.Subject) || constraint.Operands.Any(SelectionCarriesRegisteredNoun);
    }

    private static bool SelectionCarriesRegisteredNoun(Selection selection)
    {
        if (selection is UnionSelection union) return union.Parts.Any(SelectionCarriesRegisteredNoun);
        if (selection.Noun is RegisteredNoun) return true;

        return selection.Adjectives.OfType<ExceptAdjective>().Any(except => SelectionCarriesRegisteredNoun(except.Payload));
    }

    /// <summary>
    ///     A frozen scope's context card (without the provenance line, which the splice pipeline adds
    ///     once per file): the scope heading, the containment law and rationale, the load-bearing-
    ///     weirdness dragons prose (inline <c>Dragons:</c> paragraph and/or a linked <c>Dragons doc</c>
    ///     bullet — one of the two is spec-guaranteed), the sanctioned surface (omitted for
    ///     a hermetic freeze), and the <c>explain</c> pointer. This is the scoped, per-directory story the
    ///     agents editing dragon territory read.
    /// </summary>
    public static string ScopeCard(ArchRule containmentRule)
    {
        Guard.NotNull(containmentRule, nameof(containmentRule));
        if (containmentRule.Freeze is not { Role: FreezeRole.Containment } freeze)
            throw new ArgumentException("ScopeCard requires a Freeze containment rule.", nameof(containmentRule));

        string scopeId = freeze.ScopeId;

        var bullets = new List<string>
        {
            $"- {ProseFormat.Backtick(containmentRule.Id)} — {containmentRule.Sentence} {containmentRule.Because}"
        };
        if (freeze.Boundary.Count > 0) bullets.Add($"- Sanctioned surface: {SurfaceList(freeze.Boundary)}.");
        // The linked long-form doc is a backticked solution-relative path (the spec stays the index),
        // not a rebased markdown link.
        if (freeze.DragonsDoc is { } dragonsDoc) bullets.Add($"- Dragons doc: {ProseFormat.Backtick(dragonsDoc)}.");
        bullets.Add($"- Expand: {ProseFormat.Backtick($"loadbearing explain {containmentRule.Id}")}.");

        var sections = new List<string>
        {
            $"## Frozen scope {ProseFormat.Backtick(scopeId)}",
            $"This directory holds the frozen {ProseFormat.Backtick(scopeId)} scope. " +
            "Here be dragons — do not spread references into it."
        };
        if (freeze.Dragons is { } dragons) sections.Add($"Dragons: {dragons}");
        sections.Add(string.Join("\n", bullets));

        return string.Join("\n\n", sections);
    }

    /// <summary>
    ///     A layer's "local rules" context card, placed in the layer's directory (without
    ///     the provenance line, which the splice pipeline adds once per file): the layer heading, a
    ///     one-line lede, then one bullet per anchored rule — the very same Rules/Migrations composer
    ///     the root block uses, so a rule reads identically in both places — closed by a generic
    ///     drill-down pointer. No Fix lines (progressive disclosure; <c>explain</c> serves the fix).
    ///     This is the scoped, per-directory rule digest an agent editing the layer reads.
    /// </summary>
    public static string LayerCard(string layerName, IReadOnlyList<ArchRule> rules)
    {
        Guard.NotNullOrWhiteSpace(layerName, nameof(layerName));
        Guard.NotNull(rules, nameof(rules));

        var bullets = rules.Select(rule => RuleBullet(rule)).ToList();
        bullets.Add($"- Expand any rule above with {ProseFormat.Backtick("loadbearing explain <rule-id>")}.");

        var sections = new List<string>
        {
            $"## Layer {ProseFormat.Backtick(layerName)}",
            $"This directory holds the {ProseFormat.Backtick(layerName)} layer. Its architecture rules:",
            string.Join("\n", bullets)
        };

        return string.Join("\n\n", sections);
    }

    private static string LayersSection(IReadOnlyList<LayerDefinition> layers)
    {
        var bullets = layers.Select(layer => "- " + layer.DefinitionFragment);
        return "### Layers\n" + string.Join("\n", bullets);
    }

    private static string RulesSection(IReadOnlyList<ArchRule> rules)
    {
        var bullets = rules.Select(rule => RuleBullet(rule));
        return "### Rules\n" + string.Join("\n", bullets);
    }

    // The Migrate counter-prior section: one bullet per Migrate rule that names
    // the OLD pattern as grandfathered debt, states the target law, and renders the boy-scout policy —
    // so an agent reading the majority (old) pattern does not infer it is house style.
    private static string MigrationsSection(IReadOnlyList<ArchRule> rules, Func<ArchRule, int?>? counts)
    {
        var bullets = rules.Select(rule => RuleBullet(rule, counts));
        return "### Migrations\n" + string.Join("\n", bullets);
    }

    // One rule's context bullet — the shared composer for the root Rules and Migrations sections and
    // the per-layer card, so a rule renders byte-identically wherever it appears. An Enforce rule
    // states its law sentence + rationale; a Migrate rule renders the full counter-prior paragraph
    // (OLD-pattern warning, target law, boy-scout policy, and the optional live grandfathered count).
    // No Fix line ever — progressive disclosure routes fixes to `explain`.
    private static string RuleBullet(ArchRule rule, Func<ArchRule, int?>? counts = null)
    {
        return rule.Posture == Posture.Migrate
            ? MigrationBullet(rule, counts)
            : $"- {ProseFormat.Backtick(rule.Id)} — {rule.Sentence} {rule.Because}";
    }

    private static string MigrationBullet(ArchRule rule, Func<ArchRule, int?>? counts)
    {
        MigrateData migrate = rule.Migrate!;
        string bullet = $"- {ProseFormat.Backtick(rule.Id)} — Most existing code here follows the OLD pattern: " +
                        $"{migrate.From} That is grandfathered debt, not house style. New code must follow: " +
                        $"{migrate.ToSentence} {rule.Because} {PolicySentence(migrate.Policy)}";

        if (counts?.Invoke(rule) is { } remaining) bullet += $" Grandfathered sites remaining: {remaining}.";

        return bullet;
    }

    // The Freeze containment section (GRAMMAR §7): one bullet per frozen scope stating the
    // containment law + rationale + sanctioned surface, in the always-on root block because containment
    // binds code OUTSIDE the frozen directory — those agents never see the per-directory scope card.
    // Dragons prose stays scoped-only (progressive disclosure) and prints in the scope card + explain.
    private static string FrozenScopesSection(IReadOnlyList<ArchRule> containmentRules)
    {
        var bullets = containmentRules.Select(FrozenScopeBullet);
        return "### Frozen scopes\n" + string.Join("\n", bullets);
    }

    private static string FrozenScopeBullet(ArchRule rule)
    {
        FreezeData freeze = rule.Freeze!;
        var bullet = $"- {ProseFormat.Backtick(freeze.ScopeId)} — {rule.Sentence} {rule.Because}";
        if (freeze.Boundary.Count > 0) bullet += $" Sanctioned surface: {SurfaceList(freeze.Boundary)}.";
        return bullet;
    }

    private static string PolicySentence(MigrationPolicy policy)
    {
        return policy switch
        {
            MigrationPolicy.AlwaysMigrate =>
                "If your change touches a grandfathered site, migrate it as part of the change; never grow the debt.",
            MigrationPolicy.NeverExpand =>
                "Do not migrate grandfathered sites in passing (a coordinated migration is planned); never grow the debt.",
            _ => "If you are already editing a grandfathered site and the migration is small, migrate it; " +
                 "otherwise do not grow the debt."
        };
    }

    private static string SurfaceList(IReadOnlyList<Type> boundary)
    {
        return string.Join(", ", boundary.Select(type => ProseFormat.Backtick(TypeName.Simple(type))));
    }
}