using Shouldly;
using Xunit;
using Zphil.LoadBearing.Rendering;
using Zphil.LoadBearing.Tests.Checking;

namespace Zphil.LoadBearing.Tests.Rendering;

/// <summary>
///     Golden pins for the agent-context composition: the full root block for the canonical
///     sample (module map + the four Enforce laws + Migrations + the Quarantined scopes section, and the
///     §4.1 glossary line once), the no-layer single-rule root block (the dogfood shape), and the
///     canonical <c>legacy/billing</c> scope card (containment law + rationale + dragons prose +
///     sanctioned surface), plus the DragonsDoc-only card variant. Output is LF-only.
/// </summary>
public class AgentContextRendererTests
{
    // A no-layer, single Enforce-rule spec — the dogfood shape. Fix is present but never renders
    // into the always-on block (progressive disclosure).
    private static readonly IArchitectureSpec DogfoodShapeSpec = new InlineSpec(arch =>
        arch.Rule("layering/core-no-roslyn")
            .Enforce(arch.Project("Zphil.LoadBearing").MustNotReference(arch.Project("Zphil.LoadBearing.Roslyn")))
            .Because("Core is the netstandard2.0 reified model both render targets consume; " +
                     "Roslyn extraction is host machinery.")
            .Fix("Depend on the Codebase model types in Core; keep Microsoft.CodeAnalysis behind " +
                 "Zphil.LoadBearing.Roslyn."));

    // A single Migrate-rule spec — no layers, no Enforce rules — for the Migrations-section pins.
    private static IArchitectureSpec PolicySpec(MigrationPolicy policy)
    {
        return new InlineSpec(arch =>
            arch.Rule("data-access/no-inline-sql")
                .Migrate("Old pattern prose.", arch.Types.MustHaveSuffix("X"))
                .WhileYoureThere(policy)
                .Because("Because prose."));
    }

    private static ArchitectureModel Canonical()
    {
        return ArchModelBuilder.Build(new ArchSpec());
    }

    [Fact]
    public void RootBlock_CanonicalSample_MatchesGolden()
    {
        const string expected =
            "*Generated by `loadbearing render` from `CanonicalSampleSpec` — " +
            "do not edit between the markers; edit the spec and re-render.*\n\n" +
            "## Architecture (LoadBearing)\n\n" +
            "reference = a source-level type reference; construct = a source-level object creation " +
            "(`new`, including target-typed `new()`). Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
            "### Layers\n" +
            "- **Domain** — `MyApp.Domain.*`\n" +
            "- **Web** — `MyApp.Web.*`\n\n" +
            "### Rules\n" +
            "- `layering/domain-independent` — The Domain layer must not reference the Web layer. " +
            "Domain is UI-agnostic; transaction boundaries live in services.\n" +
            "- `naming/interfaces` — Interfaces in `MyApp.*` must be named `I*`. " +
            "House naming convention; agents grep by I-prefix.\n" +
            "- `naming/handlers` — Types implementing `IHandler<T>` must be named `*Handler`. " +
            "Handler discovery is convention-based (see HandlerRegistry).\n" +
            "- `di/handlers-via-registry` — Types, except `HandlerRegistry` must not construct " +
            "types implementing `IHandler<T>`. " +
            "Handlers are resolved through HandlerRegistry; direct construction bypasses discovery.\n" +
            "- `style/type-name-length` — Types in `MyApp.*` must keep type names at or under 40 characters. " +
            "Long type names break the generated architecture tables.\n\n" +
            "### Migrations\n" +
            "- `data-access/no-inline-sql` — Most existing code here follows the OLD pattern: " +
            "Controllers open SqlConnection directly (legacy Active Record style). " +
            "That is grandfathered debt, not house style. New code must follow: " +
            "Types in the Web layer named `*Controller` must not reference `SqlConnection`. " +
            "Repository pattern for testability — ADR-012. " +
            "If you are already editing a grandfathered site and the migration is small, migrate it; " +
            "otherwise do not grow the debt.\n\n" +
            "### Quarantined scopes\n" +
            "- `legacy/billing` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or `BillingFacade` " +
            "must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or `BillingFacade`. " +
            "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing. " +
            "Sanctioned surface: `IBillingFacade`, `BillingFacade`.";

        AgentContextRenderer.RootBlock(Canonical(), "CanonicalSampleSpec").ShouldBe(expected);
    }

    [Fact]
    public void RootBlock_NoLayerSingleRuleSpec_OmitsLayersSection()
    {
        ArchitectureModel model = ArchModelBuilder.Build(DogfoodShapeSpec);

        const string expected =
            "*Generated by `loadbearing render` from `Zphil.LoadBearing.ArchSpec` — " +
            "do not edit between the markers; edit the spec and re-render.*\n\n" +
            "## Architecture (LoadBearing)\n\n" +
            "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
            "### Rules\n" +
            "- `layering/core-no-roslyn` — Types in project `Zphil.LoadBearing` must not reference " +
            "types in project `Zphil.LoadBearing.Roslyn`. " +
            "Core is the netstandard2.0 reified model both render targets consume; " +
            "Roslyn extraction is host machinery.";

        AgentContextRenderer.RootBlock(model, "Zphil.LoadBearing.ArchSpec").ShouldBe(expected);
    }

    [Fact]
    public void ScopeCard_CanonicalQuarantinedScope_MatchesGolden()
    {
        ArchRule containment = Canonical().Rules.Single(rule => rule.Id == "legacy/billing/containment");

        const string expected =
            "## Quarantined scope `legacy/billing`\n\n" +
            "This directory holds the quarantined `legacy/billing` scope. " +
            "Here be dragons — do not spread references into it.\n\n" +
            "Dragons: Banker's rounding happens at line-item level, NOT invoice level. " +
            "Nightly reconciliation depends on this. Do not normalize.\n\n" +
            "- `legacy/billing/containment` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or " +
            "`BillingFacade` must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or " +
            "`BillingFacade`. Replacement scheduled (BillingV2, ADR-019); not worth stabilizing.\n" +
            "- Sanctioned surface: `IBillingFacade`, `BillingFacade`.\n" +
            "- Expand: `loadbearing explain legacy/billing/containment`.";

        AgentContextRenderer.ScopeCard(containment).ShouldBe(expected);
    }

    [Fact]
    public void ScopeCard_DragonsDocOnly_RendersBacktickedPathBullet()
    {
        // A hermetic quarantined scope documented via a linked doc rather than inline dragons prose.
        ArchRule containment = Checker.Model(arch =>
                arch.Scope("legacy/billing")
                    .Quarantine(arch.Namespace("MyApp.Legacy.Billing.*"))
                    .DragonsDoc("arch/billing-dragons.md")
                    .Because("Replacement scheduled; see the linked doc."))
            .Rules.Single(rule => rule.Id == "legacy/billing/containment");

        string card = AgentContextRenderer.ScopeCard(containment);

        // Backticked solution-relative path (the spec stays the index), not a rebased markdown link.
        card.ShouldContain("- Dragons doc: `arch/billing-dragons.md`.");
        card.ShouldNotContain("Dragons: "); // no inline dragons paragraph when only a linked doc is supplied
        // The doc bullet precedes the Expand bullet.
        card.IndexOf("Dragons doc:", StringComparison.Ordinal)
            .ShouldBeLessThan(card.IndexOf("Expand:", StringComparison.Ordinal));
    }

    [Fact]
    public void ScopeCard_NonContainmentRule_Throws()
    {
        // ScopeCard requires a Quarantine containment rule; any other rule (here an Enforce rule with no Quarantine
        // payload) is rejected before rendering (AgentContextRenderer.cs:92-93).
        var enforceRule = new ArchRule("naming/x", Posture.Enforce, "b", null, "s", null, null, null);

        Should.Throw<ArgumentException>(() => AgentContextRenderer.ScopeCard(enforceRule))
            .Message.ShouldContain("ScopeCard requires a Quarantine containment rule.");
    }

    [Fact]
    public void LayerCard_TwoEnforceRules_MatchesGolden()
    {
        // A layer with two bare-subject Enforce rules anchored on it — the layer-card golden source.
        ArchitectureModel model = Checker.Model(arch =>
        {
            Layer dispatch = arch.Layer("Dispatch", "Acme.Dispatch.*");
            arch.Rule("modules/dispatch/internals")
                .Enforce(dispatch.MustNotReference(arch.Namespace("Acme.Web.*")))
                .Because("Dispatch is a leaf module.");
            arch.Rule("modules/dispatch/outbound")
                .Enforce(dispatch.MustNotBeReferencedBy(arch.Namespace("Acme.Legacy.*")))
                .Because("Nothing legacy may depend on dispatch.");
        });
        var rules = model.Rules.Where(rule => rule.Posture == Posture.Enforce).ToList();

        const string expected =
            "## Layer `Dispatch`\n\n" +
            "This directory holds the `Dispatch` layer. Its architecture rules:\n\n" +
            "- `modules/dispatch/internals` — The Dispatch layer must not reference types in `Acme.Web.*`. " +
            "Dispatch is a leaf module.\n" +
            "- `modules/dispatch/outbound` — The Dispatch layer must not be referenced by types in `Acme.Legacy.*`. " +
            "Nothing legacy may depend on dispatch.\n" +
            "- Expand any rule above with `loadbearing explain <rule-id>`.";

        AgentContextRenderer.LayerCard("Dispatch", rules).ShouldBe(expected);
    }

    [Fact]
    public void LayerCard_MigrateRule_RendersSameCounterPriorBulletAsRoot()
    {
        // A layer carrying one Migrate rule (subject refined onto the layer) — the counter-prior bullet source.
        ArchitectureModel model = Checker.Model(arch =>
        {
            Layer web = arch.Layer("Web", "MyApp.Web.*");
            arch.Rule("data-access/no-inline-sql")
                .Migrate(
                    "Controllers build DataTables inline (legacy Active Record style).",
                    web.WithSuffix("Controller").MustNotReference(arch.Namespace("System.Data.*")))
                .Because("Repository pattern for testability.");
        });
        var migrateRules = model.Rules.Where(rule => rule.Posture == Posture.Migrate).ToList();

        // The exact counter-prior bullet the root ### Migrations section renders for this rule.
        const string counterPriorBullet =
            "- `data-access/no-inline-sql` — Most existing code here follows the OLD pattern: " +
            "Controllers build DataTables inline (legacy Active Record style). " +
            "That is grandfathered debt, not house style. New code must follow: " +
            "Types in the Web layer named `*Controller` must not reference types in `System.Data.*`. " +
            "Repository pattern for testability. " +
            "If you are already editing a grandfathered site and the migration is small, migrate it; " +
            "otherwise do not grow the debt.";

        AgentContextRenderer.RootBlock(model, "Spec").ShouldContain(counterPriorBullet);
        // The shared composer renders the Migrate rule byte-identically in the layer card (no Fix, no count).
        AgentContextRenderer.LayerCard("Web", migrateRules).ShouldContain(counterPriorBullet);
    }

    [Fact]
    public void LayerCard_EnforceRuleWithFix_OmitsFix()
    {
        // A layer whose one Enforce rule carries a Fix — proving the card omits it.
        ArchitectureModel model = Checker.Model(arch =>
        {
            Layer web = arch.Layer("Web", "MyApp.Web.*");
            arch.Rule("layering/web-not-billing")
                .Enforce(web.MustNotReference(arch.Namespace("MyApp.Legacy.Billing.*")))
                .Because("Web reaches billing only through the facade.")
                .Fix("Inject IBillingFacade instead of newing up billing types.");
        });
        var rules = model.Rules.Where(rule => rule.Posture == Posture.Enforce).ToList();

        string card = AgentContextRenderer.LayerCard("Web", rules);

        card.ShouldContain("- `layering/web-not-billing` —"); // the rule renders...
        card.ShouldNotContain("Inject IBillingFacade"); // ...but its Fix never does (progressive disclosure).
    }

    [Fact]
    public void RootBlock_WithQuarantinedScope_EmitsQuarantinedScopesSectionWithContainmentLawAndSurface()
    {
        string block = AgentContextRenderer.RootBlock(Canonical(), "Spec");

        block.ShouldContain("### Quarantined scopes");
        block.ShouldContain("- `legacy/billing` — Types in `MyApp.Legacy.Billing.*`");
        block.ShouldContain("Sanctioned surface: `IBillingFacade`, `BillingFacade`.");
        // Dragons prose stays scoped-only — it is not in the always-on root block.
        block.ShouldNotContain("Banker's rounding");
    }

    [Fact]
    public void ProvenanceLine_NamesSpecDeterministically_NoTimestamp()
    {
        AgentContextRenderer.ProvenanceLine("MyApp.ArchSpec").ShouldBe(
            "*Generated by `loadbearing render` from `MyApp.ArchSpec` — " +
            "do not edit between the markers; edit the spec and re-render.*");
    }

    [Theory]
    [InlineData(
        MigrationPolicy.MigrateIfSmall,
        "If you are already editing a grandfathered site and the migration is small, migrate it; otherwise do not grow the debt.")]
    [InlineData(
        MigrationPolicy.AlwaysMigrate,
        "If your change touches a grandfathered site, migrate it as part of the change; never grow the debt.")]
    [InlineData(
        MigrationPolicy.NeverExpand,
        "Do not migrate grandfathered sites in passing (a coordinated migration is planned); never grow the debt.")]
    public void MigrationsSection_PolicyVariants_RenderPinnedSentences(MigrationPolicy policy, string expectedSentence)
    {
        ArchitectureModel model = ArchModelBuilder.Build(PolicySpec(policy));

        AgentContextRenderer.RootBlock(model, "Spec").ShouldContain(expectedSentence);
    }

    [Fact]
    public void RootBlock_WithGrandfatheredCounts_AppendsRemainingSentence()
    {
        ArchitectureModel model = ArchModelBuilder.Build(PolicySpec(MigrationPolicy.MigrateIfSmall));

        // The optional live-count provider supplies the count the burndown sentence reports.
        AgentContextRenderer.RootBlock(model, "Spec", _ => 7).ShouldContain("Grandfathered sites remaining: 7.");
    }

    [Fact]
    public void RootBlock_MigrateOnlySpec_EmitsMigrationsWithoutRulesSection()
    {
        ArchitectureModel model = ArchModelBuilder.Build(PolicySpec(MigrationPolicy.MigrateIfSmall));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        block.ShouldContain("### Migrations");
        block.ShouldNotContain("### Rules");
        block.ShouldNotContain("### Layers");
        block.ShouldNotContain("### Quarantined scopes"); // a spec with no quarantine omits the section entirely
    }

    [Fact]
    public void RootBlock_WithMemberRule_ExtendsGlossaryWithUseEntry()
    {
        // A spec carrying a member-target rule (MustNotUse) — triggers the extended glossary line.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("time/inject-clock")
            .Enforce(arch.Types.MustNotUse(arch.Member(typeof(DateTime), nameof(DateTime.Now))))
            .Because("Wall-clock reads are untestable; inject IClock."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The member-axis "use" entry appears beside "reference" only when a member-target rule exists.
        block.ShouldContain(
            "reference = a source-level type reference; use = a source-level member access. " +
            "Expand any rule ID with `loadbearing explain <rule-id>`.");
        // It is a swap, not an addition — the member-free glossary line is gone (GRAMMAR §4.5).
        block.ShouldNotContain("reference = a source-level type reference. Expand");
    }

    [Fact]
    public void RootBlock_WithCtorRule_ExtendsGlossaryWithConstructEntry()
    {
        // A spec carrying a ctor-target rule (MustNotConstruct) — triggers the construct glossary clause.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("di/no-new-services")
            .Enforce(arch.Types.MustNotConstruct(typeof(DateTime)))
            .Because("Services are DI-resolved; direct construction bypasses the container."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The construct clause appears beside "reference" only when a MustNotConstruct rule exists (no use here).
        block.ShouldContain(
            "reference = a source-level type reference; construct = a source-level object creation " +
            "(`new`, including target-typed `new()`). Expand any rule ID with `loadbearing explain <rule-id>`.");
        block.ShouldNotContain("use = a source-level member access");
    }

    [Fact]
    public void RootBlock_WithUseAndCtorRules_ComposesAllThreeGlossaryClauses()
    {
        // A spec carrying both a member-use rule and a ctor rule — triggers the use and construct clauses together.
        ArchitectureModel model = Checker.Model(arch =>
        {
            arch.Rule("time/inject-clock")
                .Enforce(arch.Types.MustNotUse(arch.Member(typeof(DateTime), nameof(DateTime.Now))))
                .Because("Wall-clock reads are untestable; inject IClock.");
            arch.Rule("di/no-new-services")
                .Enforce(arch.Types.MustNotConstruct(typeof(DateTime)))
                .Because("Services are DI-resolved; direct construction bypasses the container.");
        });

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // All three clauses compose in axis order (reference; use; construct), then the shared tail.
        block.ShouldContain(
            "reference = a source-level type reference; use = a source-level member access; " +
            "construct = a source-level object creation (`new`, including target-typed `new()`). " +
            "Expand any rule ID with `loadbearing explain <rule-id>`.");
    }

    [Fact]
    public void RootBlock_WithInjectRule_ExtendsGlossaryWithInjectClause()
    {
        // A MustNotInject verb over a plain type — triggers the inject clause but no Registered line.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("di/no-inject-clock")
            .Enforce(arch.Types.MustNotInject(typeof(DateTime)))
            .Because("Services are DI-injected; direct dependencies bypass the container."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The inject clause appears beside "reference" when a MustNotInject rule exists (no Registered noun here).
        block.ShouldContain(
            "reference = a source-level type reference; inject = a source-level constructor-parameter dependency " +
            "(primary constructors included). Expand any rule ID with `loadbearing explain <rule-id>`.");
        // No Registered noun in this spec → no separate registered glossary line.
        block.ShouldNotContain("registered = named in a source-level container registration");
    }

    [Fact]
    public void RootBlock_WithRegisteredNounRule_EmitsSeparateRegisteredGlossaryLine()
    {
        // A Registered noun on a non-inject verb — triggers the registered line but no inject clause.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("di/registered-no-clock")
            .Enforce(arch.Registered(Lifetime.Singleton).MustNotReference(typeof(DateTime)))
            .Because("Singletons must not read the wall clock."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // A Registered noun (here on a MustNotReference subject, not MustNotInject) gates its own line.
        block.ShouldContain(
            "registered = named in a source-level container registration " +
            "(`AddSingleton`/`AddScoped`/`AddTransient`/`TryAdd*`/`AddHostedService`/`AddDbContext`/`AddHttpClient<TClient>`); " +
            "registrations made by assembly scanning, factory internals, or framework defaults are not seen.");
        // The verb is MustNotReference, not MustNotInject → no inject clause.
        block.ShouldNotContain("inject = a source-level constructor-parameter dependency");
    }

    [Fact]
    public void RootBlock_WithoutInjectOrRegistered_OmitsBothGlossaryAdditions()
    {
        // A reference-only spec carries neither a MustNotInject verb nor a Registered noun, so the block renders
        // byte-identically to before this section existed (GRAMMAR §4.7/§10 gate discipline).
        ArchitectureModel model = ArchModelBuilder.Build(DogfoodShapeSpec);

        string block = AgentContextRenderer.RootBlock(model, "Zphil.LoadBearing.ArchSpec");
        block.ShouldNotContain("inject = a source-level constructor-parameter dependency");
        block.ShouldNotContain("registered = named in a source-level container registration");
    }

    [Fact]
    public void RootBlock_WithCaptiveDependencyRule_ComposesInjectClauseRegisteredLineAndTrueSubject()
    {
        // The captive-dependency flagship — both gates fire, and the qualified subject head survives.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("di/no-captive-dependencies")
            .Enforce(arch.Registered(Lifetime.Singleton)
                .MustNotInject(arch.Registered(Lifetime.Scoped), arch.Registered(Lifetime.Transient)))
            .Because("Singletons capturing scoped/transient services leak state across scopes."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The inject clause composes into the axis-glossary line...
        block.ShouldContain(
            "reference = a source-level type reference; inject = a source-level constructor-parameter dependency " +
            "(primary constructors included). Expand any rule ID with `loadbearing explain <rule-id>`.");
        // ...and the Registered noun gates the separate registered line.
        block.ShouldContain(
            "registered = named in a source-level container registration " +
            "(`AddSingleton`/`AddScoped`/`AddTransient`/`TryAdd*`/`AddHostedService`/`AddDbContext`/`AddHttpClient<TClient>`); " +
            "registrations made by assembly scanning, factory internals, or framework defaults are not seen.");
        // The rendered law keeps its qualified subject head — never a false bare "Types, …".
        block.ShouldContain(
            "Singleton-registered types must not inject scoped-registered types or transient-registered types.");
    }

    [Fact]
    public void RootBlock_WithCatchRule_ExtendsGlossaryWithCatchClause()
    {
        // A MustNotCatch verb over a BCL exception type — triggers the catch glossary clause but no throw clause.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("errors/no-catch-ioe")
            .Enforce(arch.Types.MustNotCatch(typeof(InvalidOperationException)))
            .Because("Swallowing invalid-operation signals hides real defects."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The catch clause appears beside "reference" only when a MustNotCatch rule exists (no other axis here).
        block.ShouldContain(
            "reference = a source-level type reference; catch = a source-level `catch` clause " +
            "(a bare `catch` counts as `System.Exception`). Expand any rule ID with `loadbearing explain <rule-id>`.");
        block.ShouldNotContain("throw = a source-level `throw`");
    }

    [Fact]
    public void RootBlock_WithThrowRule_ExtendsGlossaryWithThrowClause()
    {
        // A MustOnlyThrow verb over a BCL exception type — triggers the throw glossary clause but no catch clause.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("errors/throw-domain-only")
            .Enforce(arch.Types.MustOnlyThrow(typeof(InvalidOperationException)))
            .Because("Domain code must surface only sanctioned exception types."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The throw clause appears beside "reference" only when a MustOnlyThrow rule exists (no other axis here).
        // Exact substring equality proves the strict verb emits no external-packages caveat of its own.
        block.ShouldContain(
            "reference = a source-level type reference; throw = a source-level `throw` of the thrown " +
            "expression's type (bare rethrows `throw;` are not recorded). " +
            "Expand any rule ID with `loadbearing explain <rule-id>`.");
        block.ShouldNotContain("catch = a source-level `catch`");
    }

    [Fact]
    public void RootBlock_WithUnfilteredCatchRule_ExtendsGlossaryWithTheSameCatchClause()
    {
        // A MustNotCatchUnfiltered verb over the broadest exception type — triggers the same catch glossary clause
        // the plain catch verb triggers, and no throw clause.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("errors/filter-broad-catches")
            .Enforce(arch.Types.MustNotCatchUnfiltered(typeof(Exception)))
            .Because("A broad catch names what it expects in a `when` filter."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The clause gates on the axis, not on one verb: the filter-aware catch verb renders the very same catch
        // clause MustNotCatch renders — the fact being glossed is the same fact.
        block.ShouldContain(
            "reference = a source-level type reference; catch = a source-level `catch` clause " +
            "(a bare `catch` counts as `System.Exception`). Expand any rule ID with `loadbearing explain <rule-id>`.");
        block.ShouldNotContain("throw = a source-level `throw`");
    }

    [Fact]
    public void RootBlock_WithThrowBanRule_ExtendsGlossaryWithTheSameThrowClause()
    {
        // A MustNotThrow verb over a BCL exception type — triggers the same throw glossary clause the strict
        // allow-list verb triggers, and no catch clause.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("errors/no-bare-bcl-throws")
            .Enforce(arch.Types.MustNotThrow(typeof(Exception)))
            .Because("Bare BCL exception types carry no meaning a caller can dispatch on."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // Same axis gate on the throw side: the ban polarity renders the clause the strict allow-list renders.
        block.ShouldContain(
            "reference = a source-level type reference; throw = a source-level `throw` of the thrown " +
            "expression's type (bare rethrows `throw;` are not recorded). " +
            "Expand any rule ID with `loadbearing explain <rule-id>`.");
        block.ShouldNotContain("catch = a source-level `catch`");
    }

    [Fact]
    public void RootBlock_WithoutCatchOrThrow_OmitsBothGlossaryClauses()
    {
        // A reference-only spec carries neither exception verb, so the block renders byte-identically to before
        // the catch/throw axes existed (GRAMMAR §10 gate discipline) — the two new clauses default off.
        ArchitectureModel model = ArchModelBuilder.Build(DogfoodShapeSpec);

        string block = AgentContextRenderer.RootBlock(model, "Zphil.LoadBearing.ArchSpec");
        block.ShouldNotContain("catch = a source-level `catch`");
        block.ShouldNotContain("throw = a source-level `throw`");
    }

    [Fact]
    public void RootBlock_WithExposeRule_ExtendsGlossaryWithExposeClause()
    {
        // A MustNotExpose verb over a type — triggers the expose glossary clause but no other axis.
        ArchitectureModel model = Checker.Model(arch => arch.Rule("api/no-leaky-surface")
            .Enforce(arch.Types.MustNotExpose(typeof(DateTime)))
            .Because("Public signatures must not leak infrastructure types."));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The expose clause appears beside "reference" only when a MustNotExpose rule exists (no other axis
        // here). Expose is the seventh axis — last in clause order.
        block.ShouldContain(
            "reference = a source-level type reference; expose = a public signature position " +
            "(return, parameter, or property/field/event type) on a public member of an externally visible type. " +
            "Expand any rule ID with `loadbearing explain <rule-id>`.");
        block.ShouldNotContain("catch = a source-level `catch`");
    }

    [Fact]
    public void RootBlock_WithoutExposeRule_OmitsExposeGlossaryClause()
    {
        // A spec without a MustNotExpose verb renders byte-identically to before this axis existed
        // (GRAMMAR §10 gate discipline) — the expose clause defaults off.
        ArchitectureModel model = ArchModelBuilder.Build(DogfoodShapeSpec);

        string block = AgentContextRenderer.RootBlock(model, "Zphil.LoadBearing.ArchSpec");
        block.ShouldNotContain("expose = a public signature position");
    }
}
