using Shouldly;
using Xunit;
using Zphil.LoadBearing.Rendering;

namespace Zphil.LoadBearing.Tests.Rendering;

/// <summary>
///     Golden pins for the agent-context composition (R2): the full root block for the canonical
///     sample (module map + the four Enforce laws + Migrations + the Frozen scopes section, and the
///     §4.1 glossary line once), the no-layer single-rule root block (the dogfood shape), and the
///     canonical <c>legacy/billing</c> scope card (containment law + rationale + dragons prose +
///     sanctioned surface), plus the DragonsDoc-only card variant. Output is LF-only.
/// </summary>
public class AgentContextRendererTests
{
    private static ArchitectureModel Canonical()
    {
        return ArchModelBuilder.Build(new ArchSpec());
    }

    [Fact]
    public void RootBlock_CanonicalSample_MatchesGolden()
    {
        const string expected =
            "*Generated by `loadbearing render` from `CanonicalSampleSpec` — " +
            "do not edit between the markers; edit the spec and re-render.*\n\n" +
            "## Architecture (LoadBearing)\n\n" +
            "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
            "### Layers\n" +
            "- **Domain** — `MyApp.Domain.*`\n" +
            "- **Web** — `MyApp.Web.*`\n\n" +
            "### Rules\n" +
            "- `layering/domain-independent` — The Domain layer must not reference the Web layer. " +
            "Domain is UI-agnostic; transaction boundaries live in services.\n" +
            "- `naming/interfaces` — Interfaces in `MyApp.*` must be named `I*`. " +
            "House naming convention; agents grep by I-prefix.\n" +
            "- `naming/handlers` — Types implementing `IHandler<T>` must be named `*Handler`. " +
            "Handler discovery is convention-based (see HandlerRegistry).\n" +
            "- `style/type-name-length` — Types in `MyApp.*` must keep type names at or under 40 characters. " +
            "Long type names break the generated architecture tables.\n\n" +
            "### Migrations\n" +
            "- `data-access/no-inline-sql` — Most existing code here follows the OLD pattern: " +
            "Controllers open SqlConnection directly (legacy Active Record style). " +
            "That is grandfathered debt, not house style. New code must follow: " +
            "Types in the Web layer named `*Controller` must not reference `SqlConnection`. " +
            "Repository pattern for testability — ADR-012. " +
            "If you are already editing a grandfathered site and the migration is small, migrate it; " +
            "otherwise do not grow the debt.\n\n" +
            "### Frozen scopes\n" +
            "- `legacy/billing` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or `BillingFacade` " +
            "must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or `BillingFacade`. " +
            "Replacement scheduled (BillingV2, ADR-019); not worth stabilizing. " +
            "Sanctioned surface: `IBillingFacade`, `BillingFacade`.";

        AgentContextRenderer.RootBlock(Canonical(), "CanonicalSampleSpec").ShouldBe(expected);
    }

    [Fact]
    public void RootBlock_NoLayerSingleRuleSpec_OmitsLayersSection()
    {
        ArchitectureModel model = ArchModelBuilder.Build(new DogfoodShapeSpec());

        const string expected =
            "*Generated by `loadbearing render` from `Zphil.LoadBearing.ArchSpec` — " +
            "do not edit between the markers; edit the spec and re-render.*\n\n" +
            "## Architecture (LoadBearing)\n\n" +
            "reference = a source-level type reference. Expand any rule ID with `loadbearing explain <rule-id>`.\n\n" +
            "### Rules\n" +
            "- `layering/core-no-roslyn` — Types in project `Zphil.LoadBearing` must not reference " +
            "types in project `Zphil.LoadBearing.Roslyn`. " +
            "Core is the netstandard2.0 reified model both render targets consume; " +
            "Roslyn extraction is host machinery.";

        AgentContextRenderer.RootBlock(model, "Zphil.LoadBearing.ArchSpec").ShouldBe(expected);
    }

    [Fact]
    public void ScopeCard_CanonicalFrozenScope_MatchesGolden()
    {
        ArchRule containment = Canonical().Rules.Single(rule => rule.Id == "legacy/billing/containment");

        const string expected =
            "## Frozen scope `legacy/billing`\n\n" +
            "This directory holds the frozen `legacy/billing` scope. " +
            "Here be dragons — do not spread references into it.\n\n" +
            "Dragons: Banker's rounding happens at line-item level, NOT invoice level. " +
            "Nightly reconciliation depends on this. Do not normalize.\n\n" +
            "- `legacy/billing/containment` — Types in `MyApp.Legacy.Billing.*`, except `IBillingFacade` or " +
            "`BillingFacade` must be referenced only by types in `MyApp.Legacy.Billing.*`, `IBillingFacade` or " +
            "`BillingFacade`. Replacement scheduled (BillingV2, ADR-019); not worth stabilizing.\n" +
            "- Sanctioned surface: `IBillingFacade`, `BillingFacade`.\n" +
            "- Expand: `loadbearing explain legacy/billing/containment`.";

        AgentContextRenderer.ScopeCard(containment).ShouldBe(expected);
    }

    [Fact]
    public void ScopeCard_DragonsDocOnly_RendersBacktickedPathBullet()
    {
        ArchRule containment = ArchModelBuilder.Build(new DragonsDocScopeSpec())
            .Rules.Single(rule => rule.Id == "legacy/billing/containment");

        string card = AgentContextRenderer.ScopeCard(containment);

        // Backticked solution-relative path (the spec stays the index), not a rebased markdown link.
        card.ShouldContain("- Dragons doc: `arch/billing-dragons.md`.");
        card.ShouldNotContain("Dragons: "); // no inline dragons paragraph when only a linked doc is supplied
        // The doc bullet precedes the Expand bullet.
        card.IndexOf("Dragons doc:", StringComparison.Ordinal)
            .ShouldBeLessThan(card.IndexOf("Expand:", StringComparison.Ordinal));
    }

    [Fact]
    public void RootBlock_WithFrozenScope_EmitsFrozenScopesSectionWithContainmentLawAndSurface()
    {
        string block = AgentContextRenderer.RootBlock(Canonical(), "Spec");

        block.ShouldContain("### Frozen scopes");
        block.ShouldContain("- `legacy/billing` — Types in `MyApp.Legacy.Billing.*`");
        block.ShouldContain("Sanctioned surface: `IBillingFacade`, `BillingFacade`.");
        // Dragons prose stays scoped-only — it is not in the always-on root block.
        block.ShouldNotContain("Banker's rounding");
    }

    [Fact]
    public void ProvenanceLine_NamesSpecDeterministically_NoTimestamp()
    {
        AgentContextRenderer.ProvenanceLine("MyApp.ArchSpec").ShouldBe(
            "*Generated by `loadbearing render` from `MyApp.ArchSpec` — " +
            "do not edit between the markers; edit the spec and re-render.*");
    }

    [Theory]
    [InlineData(
        MigrationPolicy.MigrateIfSmall,
        "If you are already editing a grandfathered site and the migration is small, migrate it; otherwise do not grow the debt.")]
    [InlineData(
        MigrationPolicy.AlwaysMigrate,
        "If your change touches a grandfathered site, migrate it as part of the change; never grow the debt.")]
    [InlineData(
        MigrationPolicy.NeverExpand,
        "Do not migrate grandfathered sites in passing (a coordinated migration is planned); never grow the debt.")]
    public void MigrationsSection_PolicyVariants_RenderPinnedSentences(MigrationPolicy policy, string expectedSentence)
    {
        ArchitectureModel model = ArchModelBuilder.Build(new PolicySpec(policy));

        AgentContextRenderer.RootBlock(model, "Spec").ShouldContain(expectedSentence);
    }

    [Fact]
    public void RootBlock_WithGrandfatheredCounts_AppendsRemainingSentence()
    {
        ArchitectureModel model = ArchModelBuilder.Build(new PolicySpec(MigrationPolicy.MigrateIfSmall));

        // The optional live-count provider (unwired in the CLI this phase) appends the burndown sentence.
        AgentContextRenderer.RootBlock(model, "Spec", _ => 7).ShouldContain("Grandfathered sites remaining: 7.");
    }

    [Fact]
    public void RootBlock_MigrateOnlySpec_EmitsMigrationsWithoutRulesSection()
    {
        ArchitectureModel model = ArchModelBuilder.Build(new PolicySpec(MigrationPolicy.MigrateIfSmall));

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        block.ShouldContain("### Migrations");
        block.ShouldNotContain("### Rules");
        block.ShouldNotContain("### Layers");
        block.ShouldNotContain("### Frozen scopes"); // a spec with no freeze omits the section entirely
    }

    [Fact]
    public void RootBlock_WithMemberRule_ExtendsGlossaryWithUseEntry()
    {
        ArchitectureModel model = ArchModelBuilder.Build(new MemberRuleSpec());

        string block = AgentContextRenderer.RootBlock(model, "Spec");
        // The member-axis "use" entry appears beside "reference" only when a member-target rule exists.
        block.ShouldContain(
            "reference = a source-level type reference; use = a source-level member access. " +
            "Expand any rule ID with `loadbearing explain <rule-id>`.");
        // It is a swap, not an addition — the member-free glossary line is gone (GRAMMAR §4.5).
        block.ShouldNotContain("reference = a source-level type reference. Expand");
    }

    // A single Migrate-rule spec — no layers, no Enforce rules — for the Migrations-section pins.
    private sealed class PolicySpec(MigrationPolicy policy) : IArchitectureSpec
    {
        public void Define(Arch arch)
        {
            arch.Rule("data-access/no-inline-sql")
                .Migrate("Old pattern prose.", arch.Types.MustHaveSuffix("X"))
                .WhileYoureThere(policy)
                .Because("Because prose.");
        }
    }

    // A hermetic frozen scope documented via a linked doc rather than inline dragons prose.
    private sealed class DragonsDocScopeSpec : IArchitectureSpec
    {
        public void Define(Arch arch)
        {
            arch.Scope("legacy/billing")
                .Freeze(arch.Namespace("MyApp.Legacy.Billing.*"))
                .DragonsDoc("arch/billing-dragons.md")
                .Because("Replacement scheduled; see the linked doc.");
        }
    }

    // A no-layer, single Enforce-rule spec — the dogfood shape. Fix is present but never renders
    // into the always-on block (progressive disclosure, R2).
    private sealed class DogfoodShapeSpec : IArchitectureSpec
    {
        public void Define(Arch arch)
        {
            arch.Rule("layering/core-no-roslyn")
                .Enforce(arch.Project("Zphil.LoadBearing").MustNotReference(arch.Project("Zphil.LoadBearing.Roslyn")))
                .Because("Core is the netstandard2.0 reified model both render targets consume; " +
                         "Roslyn extraction is host machinery.")
                .Fix("Depend on the Codebase model types in Core; keep Microsoft.CodeAnalysis behind " +
                     "Zphil.LoadBearing.Roslyn.");
        }
    }

    // A spec carrying a member-target rule (MustNotUse) — triggers the extended glossary line.
    private sealed class MemberRuleSpec : IArchitectureSpec
    {
        public void Define(Arch arch)
        {
            arch.Rule("time/inject-clock")
                .Enforce(arch.Types.MustNotUse(arch.Member(typeof(DateTime), nameof(DateTime.Now))))
                .Because("Wall-clock reads are untestable; inject IClock.");
        }
    }
}