using Shouldly;
using Xunit;
using Zphil.LoadBearing.Codebase;
using Zphil.LoadBearing.Rendering;
using Zphil.LoadBearing.Roslyn;
using Zphil.LoadBearing.Tests.Extraction;

namespace Zphil.LoadBearing.Tests.Rendering;

/// <summary>
///     <see cref="GraphDiagramRenderer" /> facts over the MSBuild-free fast path: the whole block shape
///     pinned once, then the pieces that can move independently — solid observed edges against dotted
///     declared-but-unobserved ones, the allow-list and deny-list filters and their precedence, an edge
///     dropped when one endpoint leaves the scope, the empty-scope placeholder, node-ID slugging with a
///     collision, the reserved-token table that the ID prefix exists for, label entity escaping, and
///     LF-internal determinism. Summaries are built from real compilations the way
///     <see cref="GraphSummarizerTests" /> builds them, so the renderer is pinned against the model
///     extraction actually produces.
/// </summary>
public sealed class GraphDiagramRendererTests
{
    private const string SolutionName = "Test.slnx";

    [Fact]
    public void Block_ObservedAndDeclaredReferences_PinsTheWholeDiagram()
    {
        // Arrange — App touches Lib (an observed edge); Orphan declares the same reference and touches
        // nothing (the dead-reference signal the text survey makes you compute by eye).
        GraphSummary summary = ThreeProjectSummary();

        // Act
        string block = GraphDiagramRenderer.Block(summary, SolutionName);

        // Assert — caption outside the fence, theme-neutral flowchart inside it, accessibility directives,
        // nodes in ordinal order, then solid edges before dotted ones.
        block.ShouldBe(
            """
            *Generated by `loadbearing render` from `Test.slnx` — do not edit between the markers; re-render to update.*

            ```mermaid
            flowchart LR
                accTitle: Codebase survey: Test.slnx
                accDescr: Projects in this solution and their cross-project references.

                p_App["App"]
                p_Lib["Lib"]
                p_Orphan["Orphan"]

                p_App --> p_Lib
                p_Orphan -.-> p_Lib
            ```
            """);
    }

    [Fact]
    public void Block_OnlyList_DrawsTheNamedProjectsAndNothingElse()
    {
        // Arrange
        GraphSummary summary = ThreeProjectSummary();

        // Act
        string block = GraphDiagramRenderer.Block(summary, SolutionName, new DiagramScope(["App", "Lib"], []));

        // Assert — Orphan leaves, and its dotted edge leaves with it.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_App[\"App\"]", "p_Lib[\"Lib\"]", "", "p_App --> p_Lib"]);
    }

    [Fact]
    public void Block_GlobInTheOnlyList_MatchesAcrossDots()
    {
        // Arrange — a project-name glob is a single token, so '*' spans dots (unlike a namespace pattern,
        // which matches one dotted segment at a time).
        GraphSummary summary = SlugCollisionSummary();

        // Act
        string block = GraphDiagramRenderer.Block(summary, SolutionName, new DiagramScope(["My.*"], []));

        // Assert — the hyphenated sibling is out; both dotted ones are in.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_My_App[\"My.App\"]", "p_My_App2[\"My.App2\"]"]);
    }

    [Fact]
    public void Block_ExcludeList_WinsOverTheOnlyList()
    {
        // Arrange
        GraphSummary summary = ThreeProjectSummary();

        // Act — Orphan is named on both lists.
        string block = GraphDiagramRenderer.Block(
            summary, SolutionName, new DiagramScope(["App", "Lib", "Orphan"], ["Orphan"]));

        // Assert
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_App[\"App\"]", "p_Lib[\"Lib\"]", "", "p_App --> p_Lib"]);
    }

    [Fact]
    public void Block_ReferenceIntoAnOutOfScopeProject_DrawsNoEdge()
    {
        // Arrange
        GraphSummary summary = ThreeProjectSummary();

        // Act — both edges point at Lib, which is out of scope.
        string block = GraphDiagramRenderer.Block(summary, SolutionName, new DiagramScope([], ["Lib"]));

        // Assert — two nodes, no phantom Lib node, no dangling edge.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_App[\"App\"]", "p_Orphan[\"Orphan\"]"]);
    }

    [Fact]
    public void Block_EmptyScope_DrawsThePlaceholderNode()
    {
        // Arrange
        GraphSummary summary = ThreeProjectSummary();

        // Act
        string block = GraphDiagramRenderer.Block(summary, SolutionName, new DiagramScope(["Nothing"], []));

        // Assert — the (none) convention the text survey uses: an empty section keeps its shape.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_none[\"(no projects in scope)\"]"]);
    }

    [Fact]
    public void Block_Passenger_IsNotDrawnAndTakesItsEdgeWithIt()
    {
        // Arrange — Lib is a passenger a ProjectReference dragged into the workspace; both other projects
        // reference it, so this also exercises the edge half.
        GraphSummary summary = ThreeProjectSummary(libMembership: false, appMembership: true, orphanMembership: true);

        // Act — no scope at all: the default is what keeps Lib out.
        string block = GraphDiagramRenderer.Block(summary, SolutionName);

        // Assert — no Lib node, and neither the observed nor the declared-but-unobserved edge into it
        // survives, because an edge is drawn only when both endpoints resolve to nodes.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_App[\"App\"]", "p_Orphan[\"Orphan\"]"]);
    }

    [Fact]
    public void Block_UnreadMembership_DrawsEveryProject()
    {
        // The fail-open contract: an unreadable solution file labels nothing, and a fence that treated
        // unknown as "not a member" would answer with an empty drawing instead of today's whole one.
        GraphSummary summary = ThreeProjectSummary();

        string block = GraphDiagramRenderer.Block(summary, SolutionName);

        MermaidBlock.Diagram(block)
            .ShouldBe([
                "p_App[\"App\"]", "p_Lib[\"Lib\"]", "p_Orphan[\"Orphan\"]", "",
                "p_App --> p_Lib", "p_Orphan -.-> p_Lib"
            ]);
    }

    [Fact]
    public void Block_OnlyListOverPassengers_NarrowsWithinTheDeclaredMembers()
    {
        // Arrange — the two knobs compose one way only: the glob selects from the declared members, and
        // naming a passenger cannot put it back.
        GraphSummary summary = ThreeProjectSummary(libMembership: false, appMembership: true, orphanMembership: true);

        // Act
        string block = GraphDiagramRenderer.Block(summary, SolutionName, new DiagramScope(["App", "Lib"], []));

        // Assert
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_App[\"App\"]"]);
    }

    [Fact]
    public void Block_EveryProjectAPassenger_DrawsThePlaceholderNode()
    {
        // Arrange — a solution whose whole loaded universe is passengers, which is what a spec-only
        // solution file would produce.
        GraphSummary summary = ThreeProjectSummary(
            libMembership: false, appMembership: false, orphanMembership: false);

        // Act
        string block = GraphDiagramRenderer.Block(summary, SolutionName);

        // Assert — the same empty-scope convention an over-narrow glob gets, rather than an empty fence.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_none[\"(no projects in scope)\"]"]);
    }

    [Fact]
    public void Block_ProjectNamesThatSlugAlike_GetDistinctNodeIds()
    {
        // Arrange — 'My-App' and 'My.App' both slug to My_App; 'My.App2' keeps its digit.
        GraphSummary summary = SlugCollisionSummary();

        // Act
        string block = GraphDiagramRenderer.Block(summary, SolutionName);

        // Assert — first come (ordinal order) keeps the plain slug and the collision takes the ordinal
        // suffix, which the underscore keeps clear of a name that genuinely ends in a digit.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_My_App[\"My-App\"]", "p_My_App_2[\"My.App\"]", "p_My_App2[\"My.App2\"]"]);
    }

    [Theory]
    // Every one of the 19 lex rules in Mermaid's flowchart grammar that matches a bare word, plus the two
    // letters its link rules read as an arrowhead. None of the 19 is anchored to the start of a statement,
    // so a project named for any of them would break the whole diagram and not merely its own node. The
    // node-ID prefix is what puts that out of reach, and this table is the pin: whatever the grammar
    // reserves, the emitted ID is not it, while the label stays the name verbatim.
    [InlineData("end", "p_end")]
    [InlineData("graph", "p_graph")]
    [InlineData("flowchart", "p_flowchart")]
    [InlineData("flowchart-elk", "p_flowchart_elk")]
    [InlineData("swimlane-beta", "p_swimlane_beta")]
    [InlineData("subgraph", "p_subgraph")]
    [InlineData("style", "p_style")]
    [InlineData("class", "p_class")]
    [InlineData("classDef", "p_classDef")]
    [InlineData("linkStyle", "p_linkStyle")]
    [InlineData("default", "p_default")]
    [InlineData("interpolate", "p_interpolate")]
    [InlineData("call", "p_call")]
    [InlineData("href", "p_href")]
    [InlineData("click", "p_click")]
    [InlineData("_self", "p__self")]
    [InlineData("_blank", "p__blank")]
    [InlineData("_parent", "p__parent")]
    [InlineData("_top", "p__top")]
    [InlineData("o", "p_o")]
    [InlineData("x", "p_x")]
    public void Block_ProjectNamedForAMermaidToken_NeverEmitsItAsANodeId(string reserved, string expectedId)
    {
        // Arrange
        CodebaseModel model = CompilationFactory.Extract(reserved, ("Reserved.cs", "namespace R; public class One {}"));

        // Act
        string block = GraphDiagramRenderer.Block(GraphSummarizer.Summarize(model), SolutionName);

        // Assert
        MermaidBlock.Diagram(block)
            .ShouldBe([$"{expectedId}[\"{reserved}\"]"]);
    }

    [Fact]
    public void Block_LabelWithMarkupCharacters_SendsThemAsEntities()
    {
        // Arrange — a double quote would close the label early, and '#' opens an entity reference. Both go
        // out as the entity Mermaid reads back as the character itself.
        CodebaseModel model = CompilationFactory.Extract("A#1", ("Odd.cs", "namespace O; public class One {}"));

        // Act
        string block = GraphDiagramRenderer.Block(GraphSummarizer.Summarize(model), SolutionName);

        // Assert — the '#' is escaped, and the ID's slug flattens it to an underscore.
        MermaidBlock.Diagram(block)
            .ShouldBe(["p_A_1[\"A#35;1\"]"]);
    }

    [Fact]
    public void Block_Rendered_IsLfInternalAndRepeatable()
    {
        // Arrange
        GraphSummary summary = ThreeProjectSummary();

        // Act
        string first = GraphDiagramRenderer.Block(summary, SolutionName);
        string second = GraphDiagramRenderer.Block(summary, SolutionName);

        // Assert — the splicer applies the target file's line ending, so the body carries none of its own,
        // and nothing in the block is derived from the clock or the tool version.
        first.ShouldNotContain("\r");
        second.ShouldBe(first);
    }

    // App references Lib and touches it; Orphan declares the same reference and touches nothing. Membership
    // defaults to unread on all three, which is what every case predating the declared-members fence wants:
    // unknown draws, so those pins are unaffected by it.
    private static GraphSummary ThreeProjectSummary(
        bool? libMembership = null, bool? appMembership = null, bool? orphanMembership = null)
    {
        CompilationInput lib = CompilationFactory.Compile("Lib", ("Lib.cs", """
                                                                            namespace Lib;
                                                                            public class Service {}
                                                                            """)) with
        {
            SolutionMember = libMembership
        };
        CompilationInput app = CompilationFactory.CompileReferencing("App", lib.Compilation, "Lib", ("App.cs", """
                                                                                                               namespace App;
                                                                                                               public class Client { public Lib.Service S; }
                                                                                                               """)) with
        {
            SolutionMember = appMembership
        };
        CompilationInput orphan = CompilationFactory.CompileReferencing("Orphan", lib.Compilation, "Lib", ("Orphan.cs", """
                                                                                                                        namespace Orphan;
                                                                                                                        public class Standalone {}
                                                                                                                        """)) with
        {
            SolutionMember = orphanMembership
        };

        return GraphSummarizer.Summarize(CodebaseExtractor.ExtractFromCompilations([lib, app, orphan]));
    }

    // Three reference-free projects: two whose names differ only in a character the slug flattens, and a
    // third carrying a digit, which survives the slug and must not be confused with the collision suffix.
    private static GraphSummary SlugCollisionSummary()
    {
        CompilationInput hyphen = CompilationFactory.Compile("My-App", ("A.cs", "namespace A; public class One {}"));
        CompilationInput dot = CompilationFactory.Compile("My.App", ("B.cs", "namespace B; public class Two {}"));
        CompilationInput digit = CompilationFactory.Compile("My.App2", ("C.cs", "namespace C; public class Three {}"));

        return GraphSummarizer.Summarize(CodebaseExtractor.ExtractFromCompilations([hyphen, dot, digit]));
    }
}
