using System.Data;
using Shouldly;
using Xunit;
using Zphil.LoadBearing.Hosting;
using Zphil.LoadBearing.Rendering;
using Zphil.LoadBearing.Tests.Checking;

namespace Zphil.LoadBearing.Tests.Rendering;

/// <summary>
///     <see cref="LawDiagramRenderer" /> facts. The whole block is pinned once over a spec that exercises
///     every construct at once, and then the pieces that can move independently: each verb's direction,
///     the Migrate switch, the quarantine box and its two degenerate cases, the double-render guard the
///     triage order exists for, the union guard, containment nesting and the collapse and incomparable
///     cases around it, the partial rule that both draws and lists, the rule whose every operand was
///     skipped and so is listed rather than left invisible, the compact list's format, the
///     node-ID prefix that keeps a place name out of Mermaid's grammar, label escaping, the empty law,
///     and determinism. Every model is built from an inline spec — no workspace, no extraction.
/// </summary>
public sealed class LawDiagramRendererTests
{
    private const string SpecName = "Shop.ArchSpec";

    [Fact]
    public void Block_ASpecExercisingEveryConstruct_PinsTheWholeDrawing()
    {
        // Arrange
        ArchitectureModel model = WholeDrawingSpec();

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — caption outside the fence, places in the order the rules named them with what contains
        // them drawn around them, edges in rule order, an adaptive legend, and the compact list under it.
        block.ShouldBe(
            """
            *Generated by `loadbearing render` from `Shop.ArchSpec`. Do not edit between the markers; edit the spec and re-render.*

            ```mermaid
            flowchart LR
                accTitle: Architecture law: Shop.ArchSpec
                accDescr: The places this spec names, the references it forbids, and the debt it grandfathers.

                s_Domain["Domain"]
                subgraph s_Web["Web"]
                    s_Shop_Web_Controllers["Shop.Web.Controllers.*"]
                end
                s_Vendor_Engine("Vendor.Engine.*")
                s_Shop_Pack["Shop.Pack.*"]
                s_System_Data_DataTable("System.Data.DataTable")
                subgraph s_Shop_Legacy_Pricing["Quarantine: legacy/pricing"]
                    s_IPricingFacade[["IPricingFacade"]]
                end

                s_Domain --x s_Web
                s_Web --x|"expose"| s_Vendor_Engine
                s_Shop_Pack -->|"only"| s_Domain
                s_Shop_Web_Controllers -.-x|"grandfathered"| s_System_Data_DataTable

                subgraph l_legend["Legend"]
                    l_ban["--x = must not reference"]
                    l_expose["--x expose = must not expose on a public signature"]
                    l_only["--> only = the only references allowed"]
                    l_debt["-.-x grandfathered = Migrate debt, with the existing sites baselined"]
                    l_quarantine["Quarantine box = a contained scope; the doubled boxes are its sanctioned surface"]
                    l_outside["Rounded box = a place named only as the target of a rule"]
                    l_nesting["A box inside a box = the inner place is part of the outer"]
                end
            ```

            Not drawn in full: `naming/interfaces`, `legacy/pricing/tripwire` (Quarantine). Expand any of them with `loadbearing explain <rule-id>`.
            """);
    }

    [Fact]
    public void Block_TheTwoBanVerbs_PointInOppositeDirections()
    {
        // Arrange — the same two places, said from each end.
        ArchitectureModel model = Checker.Model(arch =>
        {
            arch.Rule("r/out")
                .Enforce(arch.Namespace("A.*").MustNotReference(arch.Namespace("B.*")))
                .Because("x");
            arch.Rule("r/in")
                .Enforce(arch.Namespace("C.*").MustNotBeReferencedBy(arch.Namespace("D.*")))
                .Because("x");
        });

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — MustNotBeReferencedBy is the inbound voice: the operand is the source of the arrow.
        Edges(block)
            .ShouldBe(["s_A --x s_B", "s_D --x s_C"]);
    }

    [Fact]
    public void Block_TheTwoOnlyVerbs_DrawAllowEdgesAndOmitTheSelfTarget()
    {
        // Arrange — both verbs name their own subject in the allowed list, which is the permission for a
        // place to reference itself.
        ArchitectureModel model = Checker.Model(arch =>
        {
            arch.Rule("r/out")
                .Enforce(arch.Namespace("A.*").MustOnlyReference(arch.Namespace("A.*"), arch.Namespace("B.*")))
                .Because("x");
            arch.Rule("r/in")
                .Enforce(arch.Namespace("C.*").MustOnlyBeReferencedBy(arch.Namespace("C.*"), arch.Namespace("D.*")))
                .Because("x");
        });

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert
        Edges(block)
            .ShouldBe(["s_A -->|\"only\"| s_B", "s_D -->|\"only\"| s_C"]);
    }

    [Fact]
    public void Block_AnOnlyVerbNamingNothingButItself_DrawsNoEdgeAndIsListed()
    {
        // Arrange — a leaf of the reference graph, said the only way the language says it: the sole
        // permitted target is the subject.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("r/leaf")
                .Enforce(arch.Namespace("A.*").MustOnlyReference(arch.Namespace("A.*")))
                .Because("x"));

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — the self-arrow stays omitted, and the rule lands in the list rather than vanishing.
        Edges(block)
            .ShouldBeEmpty();
        block.ShouldEndWith("Not drawn in full: `r/leaf`. Expand any of them with `loadbearing explain <rule-id>`.");
    }

    [Fact]
    public void Block_AMigrateRule_SwitchesTheSameEdgeToGrandfatheredDebt()
    {
        // Arrange — one banned relation and one exposure, each as Migrate rather than Enforce.
        ArchitectureModel model = Checker.Model(arch =>
        {
            arch.Rule("r/ban")
                .Migrate("Callers reach across.", arch.Namespace("A.*").MustNotReference(arch.Namespace("B.*")))
                .Because("x");
            arch.Rule("r/expose")
                .Migrate("Engine types leak.", arch.Namespace("C.*").MustNotExpose(arch.Namespace("D.*")))
                .Because("x");
        });

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — the verb word rides along, so "grandfathered" never has to stand for two different bans.
        Edges(block)
            .ShouldBe([
                "s_A -.-x|\"grandfathered\"| s_B",
                "s_C -.-x|\"grandfathered expose\"| s_D"
            ]);
    }

    [Fact]
    public void Block_AQuarantinedScope_DrawsTheBoxAndNeverAnOnlyEdge()
    {
        // Arrange — containment desugars to MustOnlyBeReferencedBy, so a triage that reached the verb
        // switch would draw the scope's box AND an "only" edge saying the same thing twice.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Scope("legacy/pricing")
                .Quarantine(arch.Namespace("Shop.Legacy.Pricing.*"))
                .BoundaryOnlyVia(typeof(IPricingFacade), typeof(PricingFacade))
                .Dragons("Rounding happens at line-item level.")
                .Because("x"));

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — the facades sit inside the box in the spec's own Boundary order, and no edge is drawn
        // at all: the box is the whole statement.
        MermaidBlock.Diagram(block)
            .ShouldBe([
                "subgraph s_Shop_Legacy_Pricing[\"Quarantine: legacy/pricing\"]",
                "s_IPricingFacade[[\"IPricingFacade\"]]",
                "s_PricingFacade[[\"PricingFacade\"]]",
                "end",
                "",
                "subgraph l_legend[\"Legend\"]",
                "l_quarantine[\"Quarantine box = a contained scope; the doubled boxes are its sanctioned surface\"]",
                "end"
            ]);
        block.ShouldNotContain("only");
    }

    [Fact]
    public void Block_AHermeticScope_IsARectangleCarryingTheSameLabel()
    {
        // Arrange — no sanctioned surface at all, so there is nothing to draw inside the box.
        ArchitectureModel model = HermeticScopeSpec();

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert
        MermaidBlock.Diagram(block)
            .ShouldContain("s_Shop_Legacy_Pricing[\"Quarantine: legacy/pricing\"]");
    }

    [Fact]
    public void Block_TheTripwire_DrawsNothingAndIsListed()
    {
        // Arrange
        ArchitectureModel model = HermeticScopeSpec();

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — a diff-aware touch check has no constraint to draw, and it is a rule of its own, so it
        // is named rather than silently dropped.
        block.ShouldEndWith(
            "Not drawn in full: `legacy/pricing/tripwire` (Quarantine). " +
            "Expand any of them with `loadbearing explain <rule-id>`.");
    }

    [Fact]
    public void Block_AUnionSubject_IsListedAndNeverReadsTheNoun()
    {
        // Arrange — UnionSelection.Noun throws by design; this rendering at all is the pin.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("r/union")
                .Enforce(arch.AnyOf(arch.Namespace("A.*"), arch.Namespace("B.*"))
                    .MustNotReference(arch.Namespace("C.*")))
                .Because("x"));

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — nothing placed, so the fence keeps its shape through the placeholder.
        MermaidBlock.Diagram(block)
            .ShouldBe(["s_none[\"(no rules this drawing can place)\"]"]);
        block.ShouldEndWith("Not drawn in full: `r/union`. Expand any of them with `loadbearing explain <rule-id>`.");
    }

    [Fact]
    public void Block_APartialRule_DrawsItsPlaceEdgesAndIsAlsoListed()
    {
        // Arrange — one operand is a place and the other is a union, which is not.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("r/mixed")
                .Enforce(arch.Namespace("A.*")
                    .MustNotReference(
                        arch.Namespace("B.*"),
                        arch.AnyOf(arch.Namespace("C.*"), arch.Namespace("D.*"))))
                .Because("x"));

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — the arrow that can be drawn is drawn, and the list says the arrows are not all of it.
        Edges(block)
            .ShouldBe(["s_A --x s_B"]);
        block.ShouldEndWith("Not drawn in full: `r/mixed`. Expand any of them with `loadbearing explain <rule-id>`.");
    }

    [Fact]
    public void Block_ANamespaceInsideAnother_IsDrawnInsideIt()
    {
        // Arrange
        ArchitectureModel model = Checker.Model(arch =>
        {
            arch.Rule("r/one")
                .Enforce(arch.Namespace("A.*").MustNotReference(arch.Namespace("Z.*")))
                .Because("x");
            arch.Rule("r/two")
                .Enforce(arch.Namespace("A.B.*").MustNotReference(arch.Namespace("Z.*")))
                .Because("x");
        });

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert
        MermaidBlock.Diagram(block)
            .ShouldBe([
                "subgraph s_A[\"A.*\"]",
                "s_A_B[\"A.B.*\"]",
                "end",
                "s_Z(\"Z.*\")",
                "",
                "s_A --x s_Z",
                "s_A_B --x s_Z",
                "",
                "subgraph l_legend[\"Legend\"]",
                "l_ban[\"--x = must not reference\"]",
                "l_outside[\"Rounded box = a place named only as the target of a rule\"]",
                "l_nesting[\"A box inside a box = the inner place is part of the outer\"]",
                "end"
            ]);
    }

    [Fact]
    public void Block_TwoIncomparableContainers_LeaveTheNodeFlat()
    {
        // Arrange — `A.B.C.*` sits inside both `A.*` and the two-glob Split layer, and neither of those
        // contains the other, so there is no most-specific answer to nest under.
        ArchitectureModel model = Checker.Model(arch =>
        {
            Layer wide = arch.Layer("Wide", "A.*");
            Layer split = arch.Layer("Split", "A.B.*", "Q.*");
            arch.Rule("r/one")
                .Enforce(arch.Namespace("A.B.C.*").MustNotReference(arch.Namespace("Z.*")))
                .Because("x");
            arch.Rule("r/two")
                .Enforce(wide.MustNotReference(arch.Namespace("Z.*")))
                .Because("x");
            arch.Rule("r/three")
                .Enforce(split.MustNotReference(arch.Namespace("Z.*")))
                .Because("x");
        });

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — flat rather than a hierarchy the spec never declared, and no nesting legend row.
        MermaidBlock.Diagram(block)
            .ShouldBe([
                "s_A_B_C[\"A.B.C.*\"]",
                "s_Z(\"Z.*\")",
                "s_Wide[\"Wide\"]",
                "s_Split[\"Split\"]",
                "",
                "s_A_B_C --x s_Z",
                "s_Wide --x s_Z",
                "s_Split --x s_Z",
                "",
                "subgraph l_legend[\"Legend\"]",
                "l_ban[\"--x = must not reference\"]",
                "l_outside[\"Rounded box = a place named only as the target of a rule\"]",
                "end"
            ]);
    }

    [Fact]
    public void Block_ASingleGlobLayerAndItsGlob_DrawOneNodeUnderTheLayerName()
    {
        // Arrange
        ArchitectureModel model = Checker.Model(arch =>
        {
            Layer web = arch.Layer("Web", "MyApp.Web.*");
            arch.Rule("r/one")
                .Enforce(web.MustNotReference(arch.Namespace("Z.*")))
                .Because("x");
            arch.Rule("r/two")
                .Enforce(arch.Namespace("MyApp.Web.*").MustNotReference(arch.Namespace("Y.*")))
                .Because("x");
        });

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — one node, named in the spec's own vocabulary.
        MermaidBlock.Diagram(block)
            .ShouldBe([
                "s_Web[\"Web\"]",
                "s_Z(\"Z.*\")",
                "s_Y(\"Y.*\")",
                "",
                "s_Web --x s_Z",
                "s_Web --x s_Y",
                "",
                "subgraph l_legend[\"Legend\"]",
                "l_ban[\"--x = must not reference\"]",
                "l_outside[\"Rounded box = a place named only as the target of a rule\"]",
                "end"
            ]);
    }

    [Theory]
    // The same table the survey pins, for the same reason: 19 of Mermaid's flowchart lex rules match a
    // bare word and none is anchored to the start of a statement, and its link rules read a leading o or x
    // as an arrowhead. The `s_` prefix puts every place ID out of reach of both.
    [InlineData("end", "s_end")]
    [InlineData("graph", "s_graph")]
    [InlineData("flowchart", "s_flowchart")]
    [InlineData("flowchart-elk", "s_flowchart_elk")]
    [InlineData("swimlane-beta", "s_swimlane_beta")]
    [InlineData("subgraph", "s_subgraph")]
    [InlineData("style", "s_style")]
    [InlineData("class", "s_class")]
    [InlineData("classDef", "s_classDef")]
    [InlineData("linkStyle", "s_linkStyle")]
    [InlineData("default", "s_default")]
    [InlineData("interpolate", "s_interpolate")]
    [InlineData("call", "s_call")]
    [InlineData("href", "s_href")]
    [InlineData("click", "s_click")]
    [InlineData("_self", "s__self")]
    [InlineData("_blank", "s__blank")]
    [InlineData("_parent", "s__parent")]
    [InlineData("_top", "s__top")]
    [InlineData("o", "s_o")]
    [InlineData("x", "s_x")]
    public void Block_APlaceNamedForAMermaidToken_NeverEmitsItAsANodeId(string reserved, string expectedId)
    {
        // Arrange
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("r/one")
                .Enforce(arch.Project(reserved).MustNotReference(arch.Namespace("Z.*")))
                .Because("x"));

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — and no ID may begin with the two letters the link rules read as an arrowhead.
        MermaidBlock.Diagram(block)
            .ShouldContain($"{expectedId}[\"{reserved}\"]");
        IdsIn(block)
            .ShouldAllBe(id => !id.StartsWith("o", StringComparison.Ordinal)
                               && !id.StartsWith("x", StringComparison.Ordinal));
    }

    [Fact]
    public void Block_ALabelWithMarkupCharacters_SendsThemAsEntities()
    {
        // Arrange — a generic type's angle brackets would open markup inside an HTML label, and '#' opens
        // an entity reference. All go out as the entity Mermaid reads back as the character itself.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("r/one")
                .Enforce(arch.Namespace("A.*").MustNotReference(typeof(List<string>)))
                .Because("x"));

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert
        MermaidBlock.Diagram(block)
            .ShouldContain(
                "s_System_Collections_Generic_List_System_String_(\"System.Collections.Generic.List#lt;System.String#gt;\")");
    }

    [Fact]
    public void Block_ALawWithNothingPlaceable_DrawsThePlaceholderNode()
    {
        // Arrange — a naming rule has no direction to draw.
        ArchitectureModel model = Checker.Model(arch =>
            arch.Rule("naming/interfaces")
                .Enforce(arch.Types.OfKind(TypeKind.Interface).MustHavePrefix("I"))
                .Because("x"));

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — the fence's shape stays stable, and the legend disappears with the constructs it
        // would have explained.
        MermaidBlock.Diagram(block)
            .ShouldBe(["s_none[\"(no rules this drawing can place)\"]"]);
        block.ShouldNotContain("Legend");
    }

    [Fact]
    public void Block_TheCompactList_TagsEveryNonEnforcePostureAndIsEmDashFree()
    {
        // Arrange — one of each posture that cannot be drawn.
        ArchitectureModel model = Checker.Model(arch =>
        {
            arch.Rule("naming/interfaces")
                .Enforce(arch.Types.OfKind(TypeKind.Interface).MustHavePrefix("I"))
                .Because("x");
            arch.Rule("naming/suffix")
                .Migrate("Handlers are named freely.", arch.Types.MustHaveSuffix("Handler"))
                .Because("x");
            arch.Scope("legacy/pricing")
                .Quarantine(arch.AnyOf(arch.Namespace("A.*"), arch.Namespace("B.*")))
                .Dragons("Two trees, one set of dragons.")
                .Because("x");
        });

        // Act
        string block = LawDiagramRenderer.Block(model, SpecName);

        // Assert — authoring order, backticked IDs, a posture tag only where the posture is not the law,
        // and a scope whose interior is not a place is listed rather than half-drawn.
        block.ShouldEndWith(
            "Not drawn in full: `naming/interfaces`, `naming/suffix` (Migrate), " +
            "`legacy/pricing/containment` (Quarantine), `legacy/pricing/tripwire` (Quarantine). " +
            "Expand any of them with `loadbearing explain <rule-id>`.");

        // The caption and the list are prose in the file this lands in, whose em-dash allowance the survey
        // caption above them already spends. DocHygieneTests gates the rendered file; this gates the block,
        // so a caption respelled to match its siblings reds at the renderer rather than three docs away.
        block.ShouldNotContain("—");
    }

    [Fact]
    public void Block_Rendered_IsLfInternalAndRepeatable()
    {
        // Arrange
        ArchitectureModel model = WholeDrawingSpec();

        // Act
        string first = LawDiagramRenderer.Block(model, SpecName);
        string second = LawDiagramRenderer.Block(model, SpecName);

        // Assert — the splicer applies the target file's line ending, so the body carries none of its own,
        // and nothing in the block is derived from the clock or the tool version.
        first.ShouldNotContain("\r");
        second.ShouldBe(first);
    }

    // One spec carrying every construct the fence can draw: two layers, a ban between them, an exposure
    // ban out of the solution, an only-verb naming its own subject, a Migrate rule into a single type, a
    // naming rule with no direction, and a quarantined scope with one facade.
    private static ArchitectureModel WholeDrawingSpec()
    {
        return Checker.Model(arch =>
        {
            Layer domain = arch.Layer("Domain", "Shop.Domain.*");
            Layer web = arch.Layer("Web", "Shop.Web.*");

            arch.Rule("layering/domain-independent")
                .Enforce(domain.MustNotReference(web))
                .Because("The domain outlives whatever delivers it.");

            arch.Rule("api/no-engine-types")
                .Enforce(web.MustNotExpose(arch.Namespace("Vendor.Engine.*")))
                .Because("An engine type on a public signature forces every consumer to compile against it.");

            arch.Rule("packs/leaf")
                .Enforce(arch.Namespace("Shop.Pack.*").MustOnlyReference(arch.Namespace("Shop.Pack.*"), domain))
                .Because("A pack that reaches past the domain drags the tool into its consumers.");

            arch.Rule("data/no-inline-sql")
                .Migrate(
                    "Controllers build DataTables inline.",
                    arch.Namespace("Shop.Web.Controllers.*").MustNotReference(typeof(DataTable)))
                .Because("Repository pattern for testability.");

            arch.Rule("naming/interfaces")
                .Enforce(arch.Types.OfKind(TypeKind.Interface).MustHavePrefix("I"))
                .Because("`I*` stays a reliable grep for the seams.");

            arch.Scope("legacy/pricing")
                .Quarantine(arch.Namespace("Shop.Legacy.Pricing.*"))
                .BoundaryOnlyVia(typeof(IPricingFacade))
                .Dragons("Rounding happens at line-item level.")
                .Because("Replacement scheduled; not worth stabilizing.");
        });
    }

    // The same scope with no sanctioned surface at all: the degenerate quarantine, which is both a bare
    // rectangle and a rule whose tripwire draws nothing.
    private static ArchitectureModel HermeticScopeSpec()
    {
        return Checker.Model(arch =>
            arch.Scope("legacy/pricing")
                .Quarantine(arch.Namespace("Shop.Legacy.Pricing.*"))
                .Dragons("Rounding happens at line-item level.")
                .Because("x"));
    }

    // Just the edge lines, which is what a direction or posture pin is about.
    private static IReadOnlyList<string> Edges(string block)
    {
        return MermaidBlock.Diagram(block)
            .Where(line => !line.StartsWith("l_", StringComparison.Ordinal))
            .Where(line => line.Contains("--x", StringComparison.Ordinal)
                           || line.Contains("-->", StringComparison.Ordinal)
                           || line.Contains("-.-x", StringComparison.Ordinal))
            .ToList();
    }

    // Every emitted node ID, however it is shaped.
    private static IReadOnlyList<string> IdsIn(string block)
    {
        return MermaidBlock.Diagram(block)
            .Select(line => line.StartsWith("subgraph ", StringComparison.Ordinal) ? line.Substring(9) : line)
            .Select(line => new string(line.TakeWhile(character => character is '_' or >= 'a' and <= 'z' or >= 'A' and <= 'Z' or >= '0' and <= '9')
                .ToArray()))
            .Where(id => id.Length > 0)
            .ToList();
    }

    /// <summary>A sanctioned surface for the quarantine pins; only its name reaches the drawing.</summary>
    private interface IPricingFacade;

    /// <summary>The second facade, so Boundary order is observable.</summary>
    private sealed class PricingFacade : IPricingFacade;
}
